import { isImmediateLandRamp } from './packageGraph.js'
import { sequenceEligibleCombos } from './knownCombos.js'
import { landManaSources,permanentRampSupport,burstNetSources,canPay,applyCommanderLondonBottom,immediateLandRampNetSources } from './sequenceSimulator.js'
import { commanderPriorityProfile } from './commanderPair.js'
import { combinedTargetGenericReduction, targetCostReductionStats, topLibraryCheatProfile, isTopLibraryCheatTarget } from './commanderMechanics.js'

function shuffle(arr,rng=Math.random){const a=[...arr];for(let i=a.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function percentile(xs,p){if(!xs.length)return 0;const a=[...xs].sort((x,y)=>x-y),i=(a.length-1)*p,lo=Math.floor(i),hi=Math.ceil(i);return lo===hi?a[lo]:a[lo]*(hi-i)+a[hi]*(i-lo)}
const uniq=xs=>[...new Set(xs)]
const isPermanentCard=c=>!/\binstant\b|\bsorcery\b/i.test(c.type||'')
const isArtifact=c=>/\bartifact\b/i.test(c.type||'')
const isBurst=c=>c.tags.includes('burst-mana')
const isPermanentRamp=c=>{if(c.isLand||isBurst(c))return false;const landRamp=immediateLandRampNetSources(c),manaPermanent=isPermanentCard(c)&&(c.sourceColors?.length||0)>0;if(!landRamp&&!manaPermanent)return false;return (c.cmc||0)<=3||(landRamp>=2&&(c.cmc||0)<=4)}
function alwaysTappedLand(c){const o=(c.oracle||'').toLowerCase();if(!/enters(?: the battlefield)? tapped/.test(o))return false;return !/unless|you may pay|if you control|if an opponent|reveal [^.]* from your hand|as [^.]* enters/.test(o)}
function fetchLandInfo(c){if(!/\bland\b/i.test(c.type||''))return null;const o=(c.oracle||'').toLowerCase();if(!/search your library for [^.]*\b(?:basic land|plains|island|swamp|mountain|forest)\b[^.]*put [^.]*onto the battlefield/.test(o))return null;return {delayed:/put [^.]*onto the battlefield tapped/.test(o)||alwaysTappedLand(c),fabled:/if you control four or more lands, untap that land/.test(o)}}
function source(options,origin='source',extra={}){return {options:uniq(Array.isArray(options)?options:['C']),origin,...extra}}
function productionCount(c){const n=(c.name||'').toLowerCase(),o=(c.oracle||'').toLowerCase();if(n.includes('sol ring')||n.includes('mana crypt'))return 2;const m=o.match(/add ((?:\{[wubrgc]\})+)/i);if(m)return Math.max(1,(m[1].match(/\{[wubrgc]\}/gi)||[]).length);if(/add three mana/.test(o))return 3;if(/add two mana/.test(o))return 2;return 1}
function chooseCostIndices(pool,cost){if(cost<=0)return [[]];if(cost===1)return pool.map((_,i)=>[i]);const out=[];function rec(start,left,acc){if(!left){out.push([...acc]);return}for(let i=start;i<=pool.length-left;i++){acc.push(i);rec(i+1,left-1,acc);acc.pop()}}rec(0,cost,[]);return out}
function poolKey(pool){return pool.map(s=>`${s.origin}:${(s.options||[]).join('')}`).sort().join('|')}
function expandManaPools(sources){const filters=sources.filter(s=>s.filter),normal=sources.filter(s=>!s.filter);let pools=[normal];for(const f of filters){const next=[];for(const pool of pools){next.push(pool);if(f.options?.length)next.push([...pool,source(f.options,f.origin)]);for(const idxs of chooseCostIndices(pool,f.filter.cost||1)){const used=new Set(idxs),remaining=pool.filter((_,i)=>!used.has(i)),outputs=(f.filter.outputs||[]).map(opts=>source(opts,f.origin));next.push([...remaining,...outputs])}}const seen=new Set();pools=next.filter(p=>{const k=poolKey(p);if(seen.has(k))return false;seen.add(k);return true})}return pools}
function maxManaCount(sources){return Math.max(0,...expandManaPools(sources).map(p=>p.length))}
function paymentOptions(card,tax=0){const req=card.manaReq||{generic:Math.max(0,Number(card.cmc||0)),colored:[]},colored=(req.colored||[]).map(opts=>opts.length?opts:['C']),represented=Number(req.generic||0)+colored.length,total=Math.max(Number(card.cmc||represented),represented)+tax,generic=Math.max(Number(req.generic||0)+tax,total-colored.length);return {colored,generic,total}}
function concretePaymentIndices(card,sources,tax=0){const req=paymentOptions(card,tax);if(sources.length<req.total)return null;const pips=[...req.colored].sort((a,b)=>a.length-b.length),used=new Set();function place(i){if(i>=pips.length){const remaining=[];for(let s=0;s<sources.length;s++)if(!used.has(s))remaining.push(s);if(remaining.length<req.generic)return null;return new Set([...used,...remaining.slice(0,req.generic)])}for(let s=0;s<sources.length;s++){if(used.has(s)||!pips[i].some(c=>sources[s].options.includes(c)))continue;used.add(s);const result=place(i+1);if(result)return result;used.delete(s)}return null}return place(0)}
function payAndRemain(card,sources,tax=0){for(const pool of expandManaPools(sources)){const used=concretePaymentIndices(card,pool,tax);if(used)return pool.filter((_,i)=>!used.has(i))}return null}
function canPayPair(a,b,sources){const ra=paymentOptions(a),rb=paymentOptions(b),fake={cmc:ra.total+rb.total,manaReq:{generic:ra.generic+rb.generic,colored:[...ra.colored,...rb.colored],total:ra.total+rb.total}};return canPay(fake,sources)}
function permanentRampSources(c,priority,support={}){const landRamp=immediateLandRampNetSources(c),colors=support.colors?.length?support.colors:landRamp?(priority?.manaReq?.colored?.flat()||['W','U','B','R','G']):(c.sourceColors?.length?c.sourceColors:['C']);const count=landRamp||productionCount(c);return Array.from({length:count},()=>source(colors.length?colors:['C'],c.name))}
function rampValue(c){const landRamp=immediateLandRampNetSources(c),output=landRamp||productionCount(c);return output-Number(c.cmc||0)+(isArtifact(c)?0.25:0)}
function burstPriority(c){const n=c.name.toLowerCase();if(/lotus petal|elvish spirit guide|simian spirit guide|lion's eye diamond|jeweled lotus/.test(n))return 0;if(/dark ritual|cabal ritual|rite of flame|mana vault|grim monolith/.test(n))return 1;if(/culling the weak/.test(n))return 2;return 1}
function potentialSources(activeSources,hand,used,forCommander=false,battlefield=[]){const out=[...activeSources];const bursts=hand.filter(c=>!used.has(c)&&isBurst(c)).sort((a,b)=>burstPriority(a)-burstPriority(b)||a.name.localeCompare(b.name));for(const c of bursts)out.push(...burstNetSources(c,out,battlefield,forCommander));return out}
function landColors(c){const out=[];for(const s of landManaSources(c,[c]))out.push(...(s.options||[]),...((s.filter?.outputs||[]).flat()));return uniq(out.length?out:['C'])}
function chooseLand(hand,used,priority,battlefield=[]){const lands=hand.filter(c=>c.isLand&&!used.has(c));if(!lands.length)return null;const needs=new Set(priority?.manaReq?.colored?.flat()||[]),landCount=battlefield.filter(c=>c.isLand).length;return [...lands].sort((a,b)=>{const score=c=>landColors(c).filter(x=>needs.has(x)).length*5+landColors(c).length-(alwaysTappedLand(c)?2:0)-(((c.name||'').toLowerCase()==='temple of the false god'&&landCount<4)?12:0);return score(b)-score(a)})[0]}
function castableCards(hand,used,sources,pred){return hand.filter(c=>!used.has(c)&&pred(c)&&canPay(c,sources))}
function cardByName(cards,name){const n=name.toLowerCase();return cards.find(c=>c.name.toLowerCase()===n)}
function pairOperational(a,b,battlefield,currentSources,priorSources,priorHandSet){const aBoard=battlefield.includes(a),bBoard=battlefield.includes(b);if(aBoard&&bBoard)return true;if(aBoard)return canPay(b,currentSources);if(bBoard)return canPay(a,currentSources);if(canPayPair(a,b,currentSources))return true;const aWasKnown=priorHandSet.has(a),bWasKnown=priorHandSet.has(b);if(aWasKnown&&isPermanentCard(a)&&canPay(a,priorSources)&&canPay(b,currentSources))return true;if(bWasKnown&&isPermanentCard(b)&&canPay(b,priorSources)&&canPay(a,currentSources))return true;return false}
function equipmentSequencePayoffForSimulation(c){
  const o=String(c?.oracle||'').replace(/\([^)]*\)/g,' ').replace(/\s+/g,' ').trim().toLowerCase()
  return /\bwhenever you cast [^.]{0,120}\bequipment\b|\bfor each equipment you control\b/.test(o)
}
function counterKinds(c){return new Set((c?.tags||[]).filter(t=>t.startsWith('counter-kind:')).map(t=>t.slice(13)))}
function counterScopeOpponentOnly(c){const o=(c.oracle||'').toLowerCase(),cs=o.split(/[.\n;]+/).filter(s=>/put [^.]*counters? on/.test(s));return cs.length>0&&cs.every(s=>/opponent/.test(s)&&!/you control|this (?:creature|artifact|enchantment|permanent)|target (?:creature|artifact|permanent)(?! an opponent)|each creature(?! your opponents)/.test(s))}
function counterPayoffUsesOpponent(c){const o=(c.oracle||'').toLowerCase();return /opponents? (?:has|have|with) [^.]*counters?|counters? on (?:an |each )?opponents?|poison counters? (?:an |each |your )?opponents?|for each [^.]*counter [^.]*opponent/.test(o)}
function counterPairCompatible(a,b){const ak=counterKinds(a),bk=counterKinds(b);if(!ak.size||!bk.size)return false;if(counterScopeOpponentOnly(a)&&!counterPayoffUsesOpponent(b))return false;if(ak.has('wild')||bk.has('wild')||ak.has('any')||bk.has('any'))return true;for(const k of ak)if(k!=='generic'&&bk.has(k))return true;return ak.has('generic')&&bk.has('generic')}
function operationalPackage(hand,priorHand,battlefield,used,packages,currentSources,priorSources){const available=[...battlefield,...hand.filter(c=>!used.has(c)),...priorHand],priorSet=new Set(priorHand);for(const p of packages.filter(x=>x.id!=='early-commander')){const producers=(p.producerCards||[]).map(x=>cardByName(available,x.name)).filter(Boolean);let payoffs=(p.payoffCards||[]).map(x=>cardByName(available,x.name)).filter(Boolean);if(p.id==='equipment')payoffs=payoffs.filter(equipmentSequencePayoffForSimulation);for(const a of producers)for(const b of payoffs){if(a.name.toLowerCase()===b.name.toLowerCase())continue;if(p.id==='counters'&&!counterPairCompatible(a,b))continue;if(pairOperational(a,b,battlefield,currentSources,priorSources,priorSet))return {ok:true,packageId:p.id}}}return {ok:false,packageId:null}}
function comboAccessible(hand,priorHand,battlefield,used,combos,currentSources,priorSources){const eligible=sequenceEligibleCombos(combos);if(!eligible.length)return false;const available=[...battlefield,...hand.filter(c=>!used.has(c)),...priorHand],priorSet=new Set(priorHand);for(const combo of eligible){const pieces=combo.cards.map(n=>cardByName(available,n)).filter(Boolean);if(pieces.length!==combo.cards.length)continue;if(pieces.length===2&&pairOperational(pieces[0],pieces[1],battlefield,currentSources,priorSources,priorSet))return true;if(pieces.every(c=>battlefield.includes(c)||canPay(c,currentSources)))return true}return false}
function mechanicPayMulti(card,sources,onlineCommanders=[],sameTurnCommanders=[],postCommanderSources=null){if(canPay(card,sources))return true;const onlineReduction=combinedTargetGenericReduction(card,onlineCommanders);if(onlineReduction&&canPay(card,sources,0,onlineReduction))return true;const all=[...onlineCommanders,...sameTurnCommanders],allReduction=combinedTargetGenericReduction(card,all);return !!postCommanderSources&&allReduction>0&&canPay(card,postCommanderSources,0,allReduction)}
function mechanicUnlockMulti(card,sources,onlineCommanders=[],sameTurnCommanders=[],postCommanderSources=null){if(canPay(card,sources))return false;return mechanicPayMulti(card,sources,onlineCommanders,sameTurnCommanders,postCommanderSources)}
function resolveTopLibraryCheatMulti(lib,battlefield,profile){if(!profile?.look||!lib.length)return {triggered:false,hit:false,card:null,compressed:0};const looked=lib.splice(0,Math.min(profile.look,lib.length)),eligible=looked.filter(c=>isTopLibraryCheatTarget(c,profile)).sort((a,b)=>Number(b.cmc||0)-Number(a.cmc||0)||String(a.name||'').localeCompare(String(b.name||''))),chosen=eligible[0]||null;if(chosen)battlefield.push(chosen);for(const c of looked)if(c!==chosen)lib.push(c);return {triggered:true,hit:!!chosen,card:chosen,compressed:chosen?Number(chosen.cmc||0):0}}
function keepOpeningHand(hand){const lands=hand.filter(c=>c.isLand).length,early=hand.some(c=>{if(c.isLand)return false;const ramp=immediateLandRampNetSources(c);return (c.cmc||0)<=2||c.tags?.includes('fast-mana')||(ramp>0&&((c.cmc||0)<=2||lands>=3))});return lands>=2&&lands<=5&&early}
function openingHand(libBase,priority,rng){let lib=[],hand=[],mulligans=0;while(true){lib=shuffle(libBase,rng);hand=lib.splice(0,7);if(keepOpeningHand(hand)||mulligans>=2)break;mulligans++}const penalty=Math.max(0,mulligans-1),adjusted=applyCommanderLondonBottom(hand,penalty,priority);lib.push(...adjusted.bottom);return {lib,hand:adjusted.hand,mulligans,penalty}}

export function planCommanderCasts(commanders=[],cmdTurns=[],castCounts=[],sources=[]){
  const pending=commanders.map((c,i)=>({c,i})).filter(x=>cmdTurns[x.i]==null).sort((a,b)=>String(a.c?.name||'').localeCompare(String(b.c?.name||''))).map(x=>x.i)
  if(!pending.length)return {indices:[],names:[],remaining:sources}
  const orders=pending.length===2?[pending,[pending[1],pending[0]]]:[pending]
  const plans=orders.map(order=>{let remaining=sources;const indices=[];for(const i of order){const next=payAndRemain(commanders[i],remaining,(castCounts[i]||0)*2);if(next){indices.push(i);remaining=next}}return {indices,names:indices.map(i=>commanders[i].name),remaining}})
  plans.sort((a,b)=>b.indices.length-a.indices.length||a.names.join('|').localeCompare(b.names.join('|')))
  return plans[0]
}

export function simulateSequencesMulti(cards,commanders,packages,combos=[],iterations=3000,maxTurn=7,rng=Math.random){
  const cmd=(commanders||[]).filter(Boolean).slice(0,2),cmdNames=new Set(cmd.map(c=>c.name.toLowerCase())),priority=commanderPriorityProfile(cmd)
  const libBase=cards.filter(c=>!cmdNames.has(c.name.toLowerCase())||c.__keepIn99),samples=[],engineTurns=[],recoverySamples=[],firstCmdTurns=[],perCmdTurns=cmd.map(()=>[])
  const targetProfiles=cmd.map((c,i)=>({i,name:c.name,stats:targetCostReductionStats(cards,c)})).filter(x=>x.stats),cheatProfiles=cmd.map((c,i)=>({i,name:c.name,profile:topLibraryCheatProfile(c)})).filter(x=>x.profile);let targetUnlockEvents=0,cheatTriggers=0,cheatHits=0,cheatCompressed=0
  const turnStats=Array.from({length:maxTurn},()=>({cmd:0,both:0,per:cmd.map(()=>0),engine:0,interaction:0,resource:0,burst:0,commanderCheat:0,targetReduction:0,total:0}))
  for(let it=0;it<iterations;it++){
    let {lib,hand}=openingHand(libBase,priority,rng)
    const used=new Set(),battlefield=[],activeSources=[],cmdTurns=cmd.map(()=>null),castCounts=cmd.map(()=>0)
    let pendingSources=[],priorSources=[],engineTurn=null,peak=0,sum=0,recovered=false,disruptedPackageId=null
    for(let turn=1;turn<=maxTurn;turn++){
      activeSources.push(...pendingSources);pendingSources=[];const priorHand=[...hand];if(lib.length)hand.push(lib.shift())
      const land=chooseLand(hand,used,priority,battlefield);if(land){used.add(land);battlefield.push(land);const landCount=battlefield.filter(c=>c.isLand).length,sources=landManaSources(land,battlefield),fetch=fetchLandInfo(land),fetchDelayed=!!fetch&&fetch.delayed&&!(fetch.fabled&&landCount>=4);if(alwaysTappedLand(land)||fetchDelayed)pendingSources.push(...sources);else activeSources.push(...sources)}
      let turnSources=[...activeSources]
      for(let rampCasts=0;rampCasts<8;rampCasts++){
        const commanderNowSources=potentialSources(turnSources,hand,used,true,battlefield)
        if(planCommanderCasts(cmd,cmdTurns,castCounts,commanderNowSources).indices.length)break
        const rampCandidates=castableCards(hand,used,turnSources,isPermanentRamp).map(card=>({card,support:permanentRampSupport(card,hand,used,battlefield,priority)})).filter(x=>x.support).sort((a,b)=>rampValue(b.card)-rampValue(a.card)||(a.card.cmc||0)-(b.card.cmc||0))
        const rampChoice=rampCandidates[0];if(!rampChoice)break
        const ramp=rampChoice.card,support=rampChoice.support,produced=permanentRampSources(ramp,priority,support),remaining=payAndRemain(ramp,turnSources)
        if(!remaining)break
        used.add(ramp);for(const costCard of support.consume||[])used.add(costCard);if(isPermanentCard(ramp))battlefield.push(ramp)
        if(isArtifact(ramp)){activeSources.push(...produced);turnSources=[...remaining,...produced]}else{turnSources=[...remaining];pendingSources.push(...produced)}
      }
      const generalSources=potentialSources(turnSources,hand,used,false,battlefield),commanderSources=potentialSources(turnSources,hand,used,true,battlefield),onlineBefore=cmd.filter((_,i)=>cmdTurns[i]!=null&&cmdTurns[i]<turn)
      const castPlan=planCommanderCasts(cmd,cmdTurns,castCounts,commanderSources),sameTurn=castPlan.indices.map(i=>cmd[i])
      for(const i of castPlan.indices){cmdTurns[i]=turn;castCounts[i]++;battlefield.push(cmd[i])}
      let cheatCard=null,cheatTriggeredThisTurn=false
      for(const entry of cheatProfiles){const castNow=castPlan.indices.includes(entry.i),wasOnline=cmdTurns[entry.i]!=null&&cmdTurns[entry.i]<turn,triggers=(castNow&&entry.profile.onEnter?1:0)+((wasOnline||castNow&&entry.profile.haste)&&entry.profile.onAttack?1:0);for(let n=0;n<triggers;n++){const hit=resolveTopLibraryCheatMulti(lib,battlefield,entry.profile);if(hit.triggered){cheatTriggers++;cheatTriggeredThisTurn=true}if(hit.hit){cheatHits++;cheatCompressed+=hit.compressed;cheatCard=hit.card}}}
      const mechanicPay=c=>mechanicPayMulti(c,generalSources,onlineBefore,sameTurn,castPlan.remaining),targetUnlock=targetProfiles.length>0&&hand.some(c=>!used.has(c)&&mechanicUnlockMulti(c,generalSources,onlineBefore,sameTurn,castPlan.remaining));if(targetUnlock)targetUnlockEvents++
      const engine=operationalPackage(hand,priorHand,battlefield,used,packages,generalSources,priorSources);if(engine.ok&&engineTurn==null)engineTurn=turn;if(turn===4&&engine.ok)disruptedPackageId=engine.packageId
      const interaction=!!(cheatCard&&cheatCard.interaction>0)||hand.some(c=>!used.has(c)&&c.interaction>0&&mechanicPay(c)),resource=!!(cheatCard&&(cheatCard.tags.includes('draw')||cheatCard.tags.includes('recursion')))||hand.some(c=>!used.has(c)&&(c.tags.includes('draw')||c.tags.includes('recursion'))&&mechanicPay(c))
      const manaBurst=maxManaCount(generalSources)>=maxManaCount(turnSources)+2,highImpact=!!(cheatCard&&(Number(cheatCard.cmc||0)>=5||cheatCard.tags.includes('win')||cheatCard.tags.includes('cheat')))||hand.some(c=>!used.has(c)&&(c.tags.includes('extra-turn')||c.tags.includes('win')||c.tags.includes('cheat'))&&mechanicPay(c)),combo=comboAccessible(hand,priorHand,battlefield,used,combos,generalSources,priorSources),burst=manaBurst||highImpact||combo
      if(turn===5){const recast=cmd.some((c,i)=>canPay(c,commanderSources,castCounts[i]*2)),alternateEngine=engine.ok&&(!disruptedPackageId||engine.packageId!==disruptedPackageId);recovered=resource||alternateEngine||recast;recoverySamples.push(recovered?1:0)}
      const online=cmdTurns.map(x=>x!=null&&x<=turn),cmdOnline=online.some(Boolean),bothOnline=online.length===2&&online.every(Boolean),manaTempo=Math.min(1.35,maxManaCount(activeSources)/Math.max(2,turn+1)),state=100*Math.min(1,.27*manaTempo+.22*(engine.ok?1:0)+.14*(interaction?1:0)+.11*(resource?1:0)+.10*(cmdOnline?1:0)+.08*(burst?1:0)+.08*(combo?1:0))
      peak=Math.max(peak,state);sum+=state;const ts=turnStats[turn-1];ts.total++;ts.cmd+=cmdOnline?1:0;ts.both+=bothOnline?1:0;online.forEach((x,i)=>ts.per[i]+=x?1:0);ts.engine+=engine.ok?1:0;ts.interaction+=interaction?1:0;ts.resource+=resource?1:0;ts.burst+=burst?1:0;ts.commanderCheat+=cheatTriggeredThisTurn?1:0;ts.targetReduction+=targetUnlock?1:0;priorSources=[...turnSources]
    }
    const first=cmdTurns.filter(x=>x!=null).sort((a,b)=>a-b)[0];if(first!=null)firstCmdTurns.push(first);cmdTurns.forEach((x,i)=>{if(x!=null)perCmdTurns[i].push(x)});if(engineTurn!=null)engineTurns.push(engineTurn);samples.push({avg:sum/maxTurn,peak,recovered})
  }
  const avgs=samples.map(x=>x.avg),peaks=samples.map(x=>x.peak),floor=percentile(avgs,.20),median=percentile(avgs,.50),high=percentile(avgs,.80),peak=percentile(peaks,.80),q25=percentile(avgs,.25),q75=percentile(avgs,.75),iqr=q75-q25,consistency=Math.max(0,Math.min(100,100-iqr*2.2))
  const turnProfile=turnStats.map((s,i)=>({turn:i+1,commander:Math.round(s.cmd/Math.max(1,s.total)*100),bothCommanders:Math.round(s.both/Math.max(1,s.total)*100),commanders:Object.fromEntries(cmd.map((c,j)=>[c.name,Math.round(s.per[j]/Math.max(1,s.total)*100)])),engine:Math.round(s.engine/Math.max(1,s.total)*100),interaction:Math.round(s.interaction/Math.max(1,s.total)*100),resource:Math.round(s.resource/Math.max(1,s.total)*100),burst:Math.round(s.burst/Math.max(1,s.total)*100),commanderCheat:Math.round(s.commanderCheat/Math.max(1,s.total)*100),targetReduction:Math.round(s.targetReduction/Math.max(1,s.total)*100)}))
  const commanderMedianTurns=Object.fromEntries(cmd.map((c,i)=>[c.name,perCmdTurns[i].length?Math.round(percentile(perCmdTurns[i],.5)*10)/10:null]))
  const commanderMechanics={targetCostReduction:targetProfiles.length?{commanders:targetProfiles.map(x=>({name:x.name,...x.stats})),unlockRate:Math.round(targetUnlockEvents/Math.max(1,iterations*maxTurn)*1000)/10}:null,topLibraryCheat:cheatProfiles.length?{commanders:cheatProfiles.map(x=>({name:x.name,profile:x.profile})),triggers:cheatTriggers,hits:cheatHits,hitRate:Math.round(cheatHits/Math.max(1,cheatTriggers)*1000)/10,averageManaCompressed:Math.round(cheatCompressed/Math.max(1,cheatHits)*10)/10}:null}
  return {iterations,floor:Math.round(floor),median:Math.round(median),high:Math.round(high),ceiling:Math.round(high),peak:Math.round(peak),iqr:Math.round(iqr),consistency:Math.round(consistency),commanderMedianTurn:firstCmdTurns.length?Math.round(percentile(firstCmdTurns,.5)*10)/10:null,commanderMedianTurns,engineMedianTurn:engineTurns.length?Math.round(percentile(engineTurns,.5)*10)/10:null,recoveryAfterDisruption:Math.round(recoverySamples.reduce((s,x)=>s+x,0)/Math.max(1,recoverySamples.length)*100),turnProfile,commanderMechanics,commandZone:{count:cmd.length,names:cmd.map(c=>c.name),separateTax:true}}
}
