import assert from 'node:assert/strict'
import fs from 'node:fs'

const read=p=>fs.readFileSync(new URL(`../${p}`,import.meta.url),'utf8')
const main=read('src/main.jsx')
const chrome=read('src/GlobalProductChrome.jsx')
const ux=read('src/UxEnhancements.jsx')
const css=read('src/ux.css')
const cardAudit=read('src/CardSemanticAudit.jsx')
const stats=read('api/precon-stats.js')

assert.match(main,/GlobalProductChrome/)
assert.doesNotMatch(main,/publicLibraryShortcut/)
for(const route of ['/decklists-publiques','/pod','/match','/tournoi'])assert.match(chrome,new RegExp(route.replaceAll('/','\\/')))
assert.match(chrome,/Préconstruits/)
assert.match(chrome,/moyenne des scores/)
assert.match(chrome,/\/api\/precon-stats/)
assert.match(chrome,/source ambiguë/)
assert.match(stats,/aggregate-over-supported-canonical-public-precons-v2/)
assert.match(stats,/analysisVariants/)
assert.match(stats,/median:rounded\(median\(medians\)\)/)
assert.match(stats,/mean:rounded\(mean\(medians\)\)/)
assert.match(ux,/semantic model|modèle sémantique/)
assert.doesNotMatch(ux,/MODEL_ID/)
assert.match(ux,/VALIDATED_CALIBRATION/)
assert.match(css,/publicDecksRoot>\.navFrame/,'legacy public-page navigation must be visually suppressed under the shared global chrome')
assert.match(css,/uxWorkflowNav\{display:flex/,'core workflow navigation must remain visible')
assert.doesNotMatch(css,/@media\(max-width:1120px\)\{[^}]*\.uxWorkflowNav\{display:none/,'workflow links must not disappear on tablet')
assert.match(cardAudit,/deals combat damage/)
assert.match(cardAudit,/top-of-library access/)
assert.match(cardAudit,/you lose the game/)
assert.match(cardAudit,/leave-the-battlefield/)
console.log('NAVIGATION UX CONTRACT OK — global routes, canonical live public precon reference, responsive workflows, clean chrome and contextual card audit')
