import { useMemo,useState } from 'react'
import { loadAnalysisShare } from './supabaseClient.js'
import { roadmapResultFromShare,normalizedShare } from './productData.js'
import { formPods } from './engine/matchmaking.js'
import './product.css'

const lang=()=>localStorage.getItem('aeon-lang')==='fr'?'fr':'en'
const t=(en,fr)=>lang()==='fr'?fr:en
const codeOf=input=>String(input||'').trim().match(/(?:\/a\/)?([a-f0-9]{12})(?:\b|\/|$)/i)?.[1]?.toLowerCase()||''
export default function AeonMatchPage(){
  const[text,setText]=useState(''),[players,setPlayers]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(false)
  const match=useMemo(()=>players.length>=4?formPods(players,{podSize:4}):null,[players])
  async function load(){setBusy(true);setError('');try{const codes=[...new Set(text.split(/\r?\n|\s+/).map(codeOf).filter(Boolean))].slice(0,64);if(codes.length<4)throw new Error(t('Add at least four Aeon share links/codes.','Ajoute au moins quatre liens/codes Aeon.'));const rows=await Promise.all(codes.map(loadAnalysisShare));if(rows.some(x=>!x))throw new Error(t('One or more shares could not be loaded.','Un ou plusieurs partages n’ont pas pu être chargés.'));setPlayers(rows.map((row,i)=>({id:row.share_code||`p${i}`,name:normalizedShare(row).deckName,analysis:roadmapResultFromShare(row),share:row})))}catch(e){setError(e.message||String(e))}finally{setBusy(false)}}
  return <main className="productPage wide"><a className="productBack" href="/">← Aeon Scorer</a><header className="productHero"><span>AEON MATCH · P5 EXPERIMENTAL</span><h1>{t('Form better Commander tables.','Former de meilleures tables Commander.')}</h1><p>{t('Paste 4–64 Aeon share links or codes, one per line. Aeon forms tables of four using the multi-axis Pod Match model, then locally swaps assignments when it improves total mismatch.','Colle 4 à 64 liens ou codes Aeon, un par ligne. Aeon forme des tables de quatre avec le modèle Pod Match multi-axes puis échange localement les affectations quand cela réduit le mismatch total.')}</p></header><textarea className="matchInput" value={text} onChange={e=>setText(e.target.value)} placeholder={'https://…/a/abc123def456\nhttps://…/a/…'}/><button className="productPrimary" onClick={load} disabled={busy}>{busy?t('Loading shares…','Chargement…'):t('Generate tables','Générer les tables')}</button>{error&&<div className="productError">{error}</div>}{match&&<section className="podResults"><div className="podVerdict playable"><b>{match.pods.length} {t('table(s) generated','table(s) générée(s)')}</b><span>{t(`Total mismatch ${match.totalMismatch} · ${match.algorithm}`,`Mismatch total ${match.totalMismatch} · ${match.algorithm}`)}</span></div>{match.pods.map(p=><div className="podWarnings" key={p.table}><b>{t('Table','Table')} {p.table} · mismatch {p.assessment.mismatch}/100</b>{p.players.map(player=><div key={player.id}><span>{player.name}</span><small>{player.analysis.commanderNames?.join(' + ')||'—'} · median {player.analysis.profile?.median}</small></div>)}</div>)}{!!match.unassigned.length&&<p className="productNote">{t(`${match.unassigned.length} player(s) remain unassigned because the current V1 only creates complete tables of four.`,`${match.unassigned.length} joueur(s) restent sans table car la V1 ne crée que des tables complètes de quatre.`)}</p>}<p className="productNote">{t('V1 is deterministic and explainable but does not claim a global optimum. Event/session QR persistence comes after this organizer flow is validated.','La V1 est déterministe et explicable mais ne prétend pas trouver l’optimum global. La persistance session/QR viendra après validation de ce flow organisateur.')}</p></section>}</main>
}
