import { useEffect,useMemo,useState } from 'react'
import { createMatchSession,joinMatchSession,loadAnalysisShare,loadMatchSession,setMatchSessionStatus } from './supabaseClient.js'
import { roadmapResultFromShare,normalizedShare } from './productData.js'
import { formPods } from './engine/matchmaking.js'
import { buildCrossTableRepairs } from './engine/matchRepair.js'
import { buildPodIntelligence } from './engine/roadmapEngine.js'
import GameObservationForm from './GameObservationForm.jsx'
import './product.css'

const lang=()=>localStorage.getItem('aeon-lang')==='fr'?'fr':'en'
const t=(en,fr)=>lang()==='fr'?fr:en
const codeOf=input=>String(input||'').trim().match(/(?:\/a\/)?([a-f0-9]{12})(?:\b|\/|$)/i)?.[1]?.toLowerCase()||''
const sessionOf=()=>String(new URLSearchParams(location.search).get('session')||'').trim().toLowerCase().match(/^[a-f0-9]{10}$/)?.[0]||''
const tokenKey=code=>`aeon-match-organizer-${code}`
const predictionFrom=intel=>{const gap=intel?.threatAnswer?.decks?.flatMap(d=>d.turns||[]).reduce((m,x)=>Math.max(m,Number(x.gap||0)),0)||0;return {riskScore:intel?.gameQuality?.risk?.score||0,riskLevel:intel?.gameQuality?.risk?.level||'low',podMismatch:intel?.podMatch?.mismatch||0,threatGap:gap}}
export default function AeonMatchPage(){
  const sessionCode=useMemo(sessionOf,[]),[text,setText]=useState(''),[players,setPlayers]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[sessionInfo,setSessionInfo]=useState(null),[joinShare,setJoinShare]=useState(''),[sessionState,setSessionState]=useState('')
  const match=useMemo(()=>players.length>=4?formPods(players,{podSize:4}):null,[players]),repairAudit=useMemo(()=>match?buildCrossTableRepairs(match):null,[match]),tableIntelligence=useMemo(()=>match?Object.fromEntries(match.pods.map(p=>[p.table,buildPodIntelligence(p.players.map(x=>x.analysis))])):{},[match]),organizerToken=sessionCode?localStorage.getItem(tokenKey(sessionCode))||'':''
  async function rowsToPlayers(rows){setPlayers(rows.map((row,i)=>({id:row.share_code||`p${i}`,name:normalizedShare(row).deckName,analysis:roadmapResultFromShare(row),share:row})))}
  async function loadCodes(codes){const rows=await Promise.all(codes.map(loadAnalysisShare));if(rows.some(x=>!x))throw new Error(t('One or more shares could not be loaded.','Un ou plusieurs partages n’ont pas pu être chargés.'));await rowsToPlayers(rows)}
  async function loadLocal(){setBusy(true);setError('');try{const codes=[...new Set(text.split(/\r?\n|\s+/).map(codeOf).filter(Boolean))].slice(0,64);if(codes.length<4)throw new Error(t('Add at least four Aeon share links/codes.','Ajoute au moins quatre liens/codes Aeon.'));await loadCodes(codes)}catch(e){setError(e.message||String(e))}finally{setBusy(false)}}
  async function refreshSession(){if(!sessionCode)return;setBusy(true);setError('');try{const info=await loadMatchSession(sessionCode);setSessionInfo(info);await loadCodes((info.entries||[]).map(x=>x.shareCode))}catch(e){setError(e.message||String(e));setPlayers([])}finally{setBusy(false)}}
  useEffect(()=>{if(sessionCode)refreshSession()},[sessionCode])
  async function createSession(){setBusy(true);setError('');try{const x=await createMatchSession(64);localStorage.setItem(tokenKey(x.code),x.organizerToken);location.href=`/match?session=${x.code}`}catch(e){setError(e.message==='authentication_required'?t('Sign in first to create an organizer session. Players will not need an account to join.','Connecte-toi d’abord pour créer une session organisateur. Les joueurs n’auront pas besoin de compte pour la rejoindre.'):e.message||String(e))}finally{setBusy(false)}}
  async function join(){const code=codeOf(joinShare);if(!code){setSessionState(t('Paste a valid Aeon share link/code.','Colle un lien/code Aeon valide.'));return}setBusy(true);setSessionState('');try{await joinMatchSession(sessionCode,code);setJoinShare('');setSessionState(t('Joined.','Ajouté.'));await refreshSession()}catch(e){setSessionState(e.message||String(e))}finally{setBusy(false)}}
  async function setStatus(status){if(!organizerToken)return;setBusy(true);try{await setMatchSessionStatus(sessionCode,organizerToken,status);await refreshSession()}catch(e){setError(e.message||String(e))}finally{setBusy(false)}}
  const joinUrl=sessionCode?`${location.origin}/match?session=${sessionCode}`:''
  return <main className="productPage wide"><a className="productBack" href="/">← Aeon Scorer</a><header className="productHero"><span>AEON MATCH · P5 EXPERIMENTAL</span><h1>{t('Form better Commander tables.','Former de meilleures tables Commander.')}</h1><p>{t('Use a persistent event session for fast public joining, or paste 4–64 Aeon shares locally. Small complete pools up to 12 players are solved exactly; larger pools use deterministic local optimization.','Utilise une session événement persistante pour rejoindre rapidement, ou colle localement 4 à 64 partages Aeon. Les petits groupes complets jusqu’à 12 joueurs sont résolus exactement ; les plus grands utilisent une optimisation locale déterministe.')}</p></header>
  {!sessionCode&&<><div className="productActions"><button className="productPrimary" onClick={createSession} disabled={busy}>{t('Create LGS / event session','Créer une session LGS / événement')}</button></div><p className="productNote">{t('Organizer creation requires an Aeon account. Joining a session does not. The session expires after six hours and stores only public Rule 0 share codes.','La création organisateur nécessite un compte Aeon. Rejoindre une session n’en nécessite pas. La session expire après six heures et ne stocke que des codes de partage Rule 0 publics.')}</p><textarea className="matchInput" value={text} onChange={e=>setText(e.target.value)} placeholder={'https://…/a/abc123def456\nhttps://…/a/…'}/><button className="productPrimary" onClick={loadLocal} disabled={busy}>{busy?t('Loading shares…','Chargement…'):t('Generate tables locally','Générer les tables localement')}</button></>}
  {sessionCode&&<section className="rule0Tools"><div className="rule0ToolsHead"><div><span className="sectionEyebrow">FAST JOIN</span><h3>{t('Session','Session')} {sessionCode}</h3></div><small>{sessionInfo?.status||'…'} · {players.length}/{sessionInfo?.maxPlayers||64}</small></div><div className="productActions"><button onClick={()=>navigator.clipboard?.writeText(joinUrl)}>{t('Copy join link','Copier le lien')}</button>{navigator.share&&<button onClick={()=>navigator.share({title:'Aeon Match',url:joinUrl})}>{t('Share join link','Partager le lien')}</button>}<button onClick={refreshSession} disabled={busy}>{t('Refresh','Actualiser')}</button></div><p className="productNote">{joinUrl}</p>{sessionInfo?.status==='open'&&<div className="feedbackBox"><input value={joinShare} onChange={e=>setJoinShare(e.target.value)} placeholder={t('Your Aeon Rule 0 share link','Ton lien Rule 0 Aeon')}/><button onClick={join} disabled={busy}>{t('Join session','Rejoindre')}</button></div>}{sessionState&&<p className="productNote">{sessionState}</p>}{organizerToken&&<div className="productActions"><button onClick={()=>setStatus('open')}>{t('Open joins','Ouvrir')}</button><button onClick={()=>setStatus('locked')}>{t('Lock roster','Verrouiller')}</button><button onClick={()=>setStatus('closed')}>{t('Close session','Fermer')}</button></div>}<p className="productNote">{t('This link is QR-ready for the organizer’s preferred display/QR tool; Aeon itself does not send the session data to a third-party QR service.','Ce lien est prêt à être converti en QR avec l’outil d’affichage/QR choisi par l’organisateur ; Aeon n’envoie pas les données de session à un service QR tiers.')}</p></section>}
  {error&&<div className="productError">{error}</div>}{match&&<section className="podResults"><div className="podVerdict playable"><b>{match.pods.length} {t('table(s) generated','table(s) générée(s)')}</b><span>{t(`Total mismatch ${match.totalMismatch} · ${match.algorithm}`,`Mismatch total ${match.totalMismatch} · ${match.algorithm}`)}</span></div>{match.pods.map(p=>{const intel=tableIntelligence[p.table],prediction=predictionFrom(intel);return <div className="podWarnings" key={p.table}><b>{t('Table','Table')} {p.table} · mismatch {p.assessment.mismatch}/100</b>{p.players.map(player=><div key={player.id}><span>{player.name}</span><small>{player.analysis.commanderNames?.join(' + ')||'—'} · median {player.analysis.profile?.median}</small></div>)}{intel&&<div><span>{t('Game quality','Qualité de partie')}</span><small>{intel.gameQuality.compatibility} · {intel.gameQuality.risk.level} {intel.gameQuality.risk.score}/100</small></div>}<GameObservationForm rows={p.players.map(x=>x.share).filter(Boolean)} podModelVersion={intel?.modelVersion||'pod-intelligence-v3'} prediction={prediction}/></div>})}{match.pods.length>1&&repairAudit&&<div className="podWarnings"><b>{t('Pod Repair audit','Audit Pod Repair')} · {repairAudit.modelVersion}</b>{repairAudit.repairs.length?repairAudit.repairs.map((r,i)=><div key={`${r.tableA}-${r.swap.aId}-${r.tableB}-${r.swap.bId}`}><span>{t('Suggested cross-table swap','Échange inter-table suggéré')} #{i+1}</span><small>{t('Table','Table')} {r.tableA}: {r.swap.aName} ↔ {t('Table','Table')} {r.tableB}: {r.swap.bName} · {r.before.total} → {r.after.total} (−{r.improvement})</small></div>):<div><span>{t('No better one-swap repair found','Aucun meilleur échange simple trouvé')}</span><small>{t(`${repairAudit.evaluatedSwaps} cross-table 1↔1 swaps audited.`,`${repairAudit.evaluatedSwaps} échanges inter-table 1↔1 audités.`)}</small></div>}</div>}{!!match.unassigned.length&&<p className="productNote">{t(`${match.unassigned.length} player(s) remain unassigned because only complete tables of four are generated.`,`${match.unassigned.length} joueur(s) restent sans table car seules les tables complètes de quatre sont générées.`)}</p>}<p className="productNote">{match.optimality==='exact-for-current-objective'?t('This small pool is the exact optimum for the current Aeon Match objective; Pod Repair still audits the remaining one-swap neighborhood as an explicit proof check.','Ce petit groupe est l’optimum exact pour l’objectif Aeon Match actuel ; Pod Repair audite tout de même le voisinage des échanges simples comme contrôle explicite.'):t('Large-pool matchmaking is deterministic and locally optimized. Pod Repair audits whether any remaining single cross-table swap improves that local solution.','Le matchmaking des grands groupes est déterministe et optimisé localement. Pod Repair audite si un échange inter-table simple peut encore améliorer cette solution locale.')}</p></section>}</main>
}
