import { useMemo,useState } from 'react'
import { featureDeck } from './engine/cardFeatures.js'
import { visibleTagLabels } from './uxCopy.js'

const t=(lang,en,fr)=>lang==='fr'?fr:en
function caution(card,lang){
  const o=String(card.oracle||'').toLowerCase(),tags=card.tags||[]
  if(/you lose the game/.test(o))return t(lang,'Major downside: the “lose the game” mode is real gameplay context and is not fully priced by a simple positive role list.','Risque majeur : le mode « vous perdez la partie » fait partie du contexte réel et ne peut pas être résumé par une simple liste de rôles positifs.')
  if(tags.includes('etb')&&/leaves? the battlefield|when .* leaves/.test(o))return t(lang,'ETB and leave-the-battlefield effects are coupled: blink can be beneficial, neutral or harmful depending on sequencing.','L’arrivée en jeu et le départ sont couplés : le blink peut être bénéfique, neutre ou pénalisant selon la séquence.')
  if(tags.includes('protection')&&/\b(?:this creature|[a-z' -]+) has [^.]*indestructible/.test(o)&&!/target [^.]* gains? [^.]*indestructible|creatures? you control [^.]*indestructible|other [^.]*indestructible/.test(o))return t(lang,'The protection signal appears to describe this card’s own durability, not protection granted to your engine.','Le signal « protection » semble surtout décrire la résistance propre de cette carte, pas une protection accordée à ton moteur.')
  if(tags.includes('draw')&&(/discard (?:a|two|three|\d+)|you lose \d+ life|lose \d+ life/.test(o)))return t(lang,'Card advantage has a meaningful discard/life cost; Aeon detects the resource role but the trade-off is contextual.','L’avantage de cartes a un coût réel en défausse/vie ; Aeon détecte le rôle de ressource mais ce compromis reste contextuel.')
  if(/impending/.test(o))return t(lang,'Alternate timing/cost detected: exact board-state timing remains an approximation.','Coût/tempo alternatif détecté : le moment exact où la carte devient pleinement active reste une approximation.')
  if(tags.includes('stax')&&/can't attack you unless/.test(o))return t(lang,'Defensive temporary restriction: “stax” is a broad engine tag, not a claim that this card hard-locks the table.','Restriction défensive temporaire : « stax » est un tag moteur large, pas l’affirmation que cette carte verrouille la table.')
  if(tags.includes('lifegain')&&/otherwise,? you lose|if you control a demon/.test(o))return t(lang,'Life gain is conditional; the same card can also cost life.','Le gain de vie est conditionnel ; la même carte peut aussi coûter des points de vie.')
  return ''
}

export default function CardSemanticAudit({cards=[],lang='en'}){
  const[query,setQuery]=useState(''),featured=useMemo(()=>featureDeck(cards),[cards]),rows=useMemo(()=>featured.map(card=>({card,roles:visibleTagLabels(card.tags,lang,8),caution:caution(card,lang)})).filter(x=>!query||x.card.name.toLowerCase().includes(query.toLowerCase())||x.roles.join(' ').toLowerCase().includes(query.toLowerCase())),[featured,query,lang]),flagged=rows.filter(x=>x.caution).length
  return <details className="cardAudit aeonLabSection"><summary><span><b>{t(lang,'Card-by-card semantic audit','Audit sémantique carte par carte')}</b><small>{t(lang,`${featured.length} cards · ${flagged} contextual warnings`,`${featured.length} cartes · ${flagged} alertes contextuelles`)}</small></span><i>+</i></summary><div className="cardAuditBody"><p>{t(lang,'This view shows what Aeon actually recognized on every card. A contextual warning does not automatically mean the score is wrong; it identifies cards whose downside, timing or paired effects deserve human review.','Cette vue montre ce qu’Aeon a réellement reconnu sur chaque carte. Une alerte contextuelle ne signifie pas automatiquement que le score est faux ; elle signale les cartes dont le coût, le timing ou les effets couplés méritent une vérification humaine.')}</p><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t(lang,'Search a card or role…','Chercher une carte ou un rôle…')}/><div className="cardAuditTable"><div className="cardAuditHead"><span>{t(lang,'Card','Carte')}</span><span>{t(lang,'Recognized roles','Rôles reconnus')}</span><span>{t(lang,'Context review','Vérification contextuelle')}</span></div>{rows.map(({card,roles,caution})=><div className={`cardAuditRow${caution?' flagged':''}`} key={`${card.name}-${card.cmc}`}><span><b>{card.name}</b><small>MV {Number(card.cmc||0)}</small></span><span>{roles.length?roles.join(' · '):t(lang,'No strong functional role exposed','Aucun rôle fonctionnel fort exposé')}</span><span>{caution||'—'}</span></div>)}</div></div></details>
}
