import { useMemo,useState } from 'react'
import { featureDeck } from './engine/cardFeatures.js'
import { cardContextFlags } from './engine/cardContext.js'
import { visibleTagLabels } from './uxCopy.js'

const t=(lang,en,fr)=>lang==='fr'?fr:en
export function cardAuditCaution(card,lang='en'){
  const o=String(card.oracle||'').toLowerCase(),tags=card.tags||[],flags=new Set(cardContextFlags(card)),topLibrary=(tags.includes('cheat')||tags.includes('free'))&&/(?:play lands|cast spells|play cards) from the top|top card of your library/.test(o)
  if(flags.has('lose-game'))return t(lang,'Major downside: a real “lose the game” clause is present. Aeon exposes it explicitly instead of presenting only the card’s positive roles.','Risque majeur : une vraie clause « vous perdez la partie » est présente. Aeon l’expose explicitement au lieu de ne montrer que les rôles positifs de la carte.')
  if(flags.has('harmful-leave'))return t(lang,'Leaving the battlefield carries a major self-penalty. Blink, bounce or sacrifice can therefore reverse the apparent upside depending on sequencing.','Quitter le champ de bataille entraîne une forte pénalité pour toi. Blink, bounce ou sacrifice peuvent donc inverser l’avantage apparent selon la séquence.')
  if(flags.has('recurring-sacrifice')||flags.has('recurring-discard'))return t(lang,'This card carries a recurring resource cost (sacrifice/discard). Its positive role is real, but it is not free value.','Cette carte impose un coût de ressource récurrent (sacrifice/défausse). Son rôle positif est réel, mais ce n’est pas de la value gratuite.')
  if(flags.has('recurring-life-loss'))return t(lang,'The effect repeatedly spends life. Aeon recognizes the upside but also marks the recurring life-pressure as context.','L’effet consomme régulièrement des points de vie. Aeon reconnaît l’avantage mais signale aussi cette pression récurrente sur les PV.')
  if(flags.has('temporary-removal'))return t(lang,'The removal is temporary and tied to this permanent remaining on the battlefield; removing it can return the exiled threat.','Le retrait est temporaire et dépend du maintien de ce permanent sur le champ de bataille ; le retirer peut faire revenir la menace exilée.')
  if(flags.has('alternate-timing')&&flags.has('draw-discard'))return t(lang,'Alternate timing/cost and draw-discard filtering are both relevant here; exact board-state timing remains an approximation.','Coût/tempo alternatif et filtrage pioche-défausse comptent tous les deux ici ; le moment exact où la carte devient pleinement active reste une approximation.')
  if(flags.has('alternate-timing'))return t(lang,'Alternate timing/cost detected: exact board-state timing remains an approximation.','Coût/tempo alternatif détecté : le moment exact où la carte devient pleinement active reste une approximation.')
  if(flags.has('defensive-tax'))return t(lang,'Defensive temporary restriction: “stax” is a broad engine tag, not a claim that this card hard-locks the table.','Restriction défensive temporaire : « stax » est un tag moteur large, pas l’affirmation que cette carte verrouille la table.')
  if(flags.has('conditional-lifegain'))return t(lang,'Life gain is conditional; the same card can also cost life.','Le gain de vie est conditionnel ; la même carte peut aussi coûter des points de vie.')
  if(flags.has('combat-gated-draw')&&flags.has('draw-discard'))return t(lang,'Card access first requires connecting in combat, and that access is filtering (draw then discard), not unconditional card advantage.','L’accès aux cartes demande d’abord de toucher en combat, et cet accès est du filtrage (piocher puis défausser), pas de l’avantage de cartes inconditionnel.')
  if(flags.has('self-only-protection')&&flags.has('life-payment'))return t(lang,'The protection mainly keeps this card itself alive and asks you to spend life; it is not broad protection for the rest of the engine.','La protection sert surtout à garder cette carte elle-même en vie et demande de payer des PV ; ce n’est pas une protection globale du reste du moteur.')
  if(flags.has('self-only-protection'))return t(lang,'The protection signal mainly describes this card’s own durability, not protection granted to your engine.','Le signal « protection » décrit surtout la résistance propre de cette carte, pas une protection accordée à ton moteur.')
  if(flags.has('life-payment')&&topLibrary)return t(lang,'The alternate casting access uses your life as payment, while the card also provides top-of-library access; “free” here means cost substitution/compression, not literally zero cost.','L’accès alternatif aux sorts se paie avec tes PV et la carte donne aussi accès au dessus de la bibliothèque ; « gratuit » signifie ici substitution/compression de coût, pas coût réellement nul.')
  if(flags.has('draw-discard')&&flags.has('life-payment'))return t(lang,'Draw-discard filtering and a separate life payment are both present. Aeon keeps those trade-offs visible instead of presenting the positive roles as unconditional value.','Filtrage pioche-défausse et paiement de PV sont tous les deux présents. Aeon garde ces contreparties visibles au lieu de présenter les rôles positifs comme de la value inconditionnelle.')
  if(flags.has('draw-discard'))return t(lang,'The draw signal is causally coupled to discarding/filtering; Aeon recognizes card access without presenting it as pure unconditional card advantage.','Le signal de pioche est réellement couplé à de la défausse/du filtrage ; Aeon reconnaît l’accès aux cartes sans le présenter comme du pur avantage de cartes inconditionnel.')
  if(flags.has('life-payment'))return t(lang,'One of this card’s effects asks its controller to spend life. Opponent-paid Ward costs are excluded from this warning.','Un des effets de cette carte demande à son contrôleur de payer des PV. Les coûts de Ward payés par l’adversaire sont exclus de cette alerte.')
  if(flags.has('combat-gated-draw'))return t(lang,'The draw signal is combat-damage gated. Aeon recognizes the role, but access depends on connecting in combat first.','Le signal de pioche dépend de blessures de combat. Aeon reconnaît le rôle, mais il faut d’abord réussir à toucher un joueur en combat.')
  if(topLibrary)return t(lang,'This card is more than a free-cast effect: it also provides sustained top-of-library access, which the short role list can under-describe.','Cette carte ne se résume pas à un lancement gratuit : elle fournit aussi un accès continu au dessus de la bibliothèque, que la liste courte de rôles peut sous-décrire.')
  return ''
}

export default function CardSemanticAudit({cards=[],lang='en'}){
  const[query,setQuery]=useState(''),featured=useMemo(()=>featureDeck(cards),[cards]),rows=useMemo(()=>featured.map(card=>({card,roles:visibleTagLabels(card.tags,lang,8),caution:cardAuditCaution(card,lang)})).filter(x=>!query||x.card.name.toLowerCase().includes(query.toLowerCase())||x.roles.join(' ').toLowerCase().includes(query.toLowerCase())),[featured,query,lang]),flagged=rows.filter(x=>x.caution).length
  return <details className="cardAudit aeonLabSection"><summary><span><b>{t(lang,'Card-by-card semantic audit','Audit sémantique carte par carte')}</b><small>{t(lang,`${featured.length} cards · ${flagged} contextual warnings`,`${featured.length} cartes · ${flagged} alertes contextuelles`)}</small></span><i>+</i></summary><div className="cardAuditBody"><p>{t(lang,'This view shows what Aeon actually recognized on every card. A contextual warning does not automatically mean the score is wrong; it identifies cards whose downside, timing, gating or paired effects deserve human review.','Cette vue montre ce qu’Aeon a réellement reconnu sur chaque carte. Une alerte contextuelle ne signifie pas automatiquement que le score est faux ; elle signale les cartes dont le coût, le timing, les conditions d’accès ou les effets couplés méritent une vérification humaine.')}</p><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t(lang,'Search a card or role…','Chercher une carte ou un rôle…')}/><div className="cardAuditTable"><div className="cardAuditHead"><span>{t(lang,'Card','Carte')}</span><span>{t(lang,'Recognized roles','Rôles reconnus')}</span><span>{t(lang,'Context review','Vérification contextuelle')}</span></div>{rows.map(({card,roles,caution})=><div className={`cardAuditRow${caution?' flagged':''}`} key={`${card.name}-${card.cmc}`}><span><b>{card.name}</b><small>MV {Number(card.cmc||0)}</small></span><span>{roles.length?roles.join(' · '):t(lang,'No strong functional role exposed','Aucun rôle fonctionnel fort exposé')}</span><span>{caution||'—'}</span></div>)}</div></div></details>
}
