import { useEffect,useMemo,useState } from 'react'
import { analysisHistory,deleteDeck,hashDeck,listDecks,recordAnalysis,restoreSession,saveDeck,signIn,signOut,signUp } from './supabaseClient.js'

const ENGINE_VERSION='3.2.0'
const SEMANTIC_VERSION='3.2.0-semantic-1'
const t=(lang,en,fr)=>lang==='fr'?fr:en
const language=()=>localStorage.getItem('aeon-lang')==='fr'?'fr':'en'
const nativeSet=(el,value)=>{if(!el)return;const proto=el instanceof HTMLTextAreaElement?HTMLTextAreaElement.prototype:HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(proto,'value')?.set?.call(el,value);el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}))}
const currentInput=()=>({decklist:document.getElementById('decklist')?.value||'',commander:document.getElementById('commander')?.value||''})
const when=x=>x?new Intl.DateTimeFormat(language()==='fr'?'fr-FR':'en-US',{dateStyle:'medium',timeStyle:'short'}).format(new Date(x)):'—'

function AuthPanel({lang,onDone}){
 const[mode,setMode]=useState('signin'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
 async function submit(e){e.preventDefault();setBusy(true);setMessage('');try{if(mode==='signup'){const out=await signUp(email,password);if(out.session)onDone(out.session);else setMessage(t(lang,'Account created. Check your email to confirm it, then sign in.','Compte créé. Confirme-le via l’e-mail reçu, puis connecte-toi.'))}else onDone(await signIn(email,password))}catch(e){setMessage(e.message||String(e))}finally{setBusy(false)}}
 return <div className="cloudAuth"><h3>{mode==='signup'?t(lang,'Create your Aeon account','Créer ton compte Aeon'):t(lang,'Sign in to Aeon','Connexion à Aeon')}</h3><p>{t(lang,'Save decklists, keep every analysis version and re-run them when the engine improves.','Sauvegarde tes decklists, conserve chaque version d’analyse et relance-les quand le moteur évolue.')}</p><form onSubmit={submit}><label>Email<input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>{t(lang,'Password','Mot de passe')}<input type="password" autoComplete={mode==='signup'?'new-password':'current-password'} minLength={6} value={password} onChange={e=>setPassword(e.target.value)} required/></label><button className="cloudPrimary" disabled={busy}>{busy?t(lang,'Please wait…','Patiente…'):mode==='signup'?t(lang,'Create account','Créer le compte'):t(lang,'Sign in','Se connecter')}</button></form>{message&&<p className="cloudMessage">{message}</p>}<button className="cloudLink" onClick={()=>{setMode(mode==='signup'?'signin':'signup');setMessage('')}}>{mode==='signup'?t(lang,'Already have an account? Sign in','Déjà un compte ? Se connecter'):t(lang,'No account yet? Create one','Pas encore de compte ? En créer un')}</button></div>
}

function DeckRow({deck,lang,onLoad,onDelete}){
 const h=deck.latest
 return <article className="cloudDeck"><div><b>{deck.name}</b><span>{deck.commander_name||'Commander'}</span></div>{h?<div className="cloudDeckScore"><strong>{h.median??'—'}</strong><span>{h.p20??'—'}–{h.p80??'—'} · {t(lang,'peak','pic')} {h.peak??'—'}</span></div>:<span className="cloudNoRun">{t(lang,'Never analyzed','Jamais analysé')}</span>}<small>{h?`${h.engine_version} · ${when(h.created_at)}`:deck.latest_analysis_at?when(deck.latest_analysis_at):t(lang,'Saved decklist','Decklist sauvegardée')}</small><div className="cloudDeckActions"><button onClick={()=>onLoad(deck)}>{t(lang,'Load','Charger')}</button><button className="danger" onClick={()=>onDelete(deck)}>{t(lang,'Delete','Supprimer')}</button></div></article>
}

export default function CloudWorkspace({children}){
 const[session,setSession]=useState(null),[ready,setReady]=useState(false),[open,setOpen]=useState(false),[decks,setDecks]=useState([]),[busy,setBusy]=useState(false),[active,setActive]=useState(null),[saveName,setSaveName]=useState(''),[notice,setNotice]=useState(''),[langTick,setLangTick]=useState(0)
 const lang=useMemo(()=>{langTick;return language()},[langTick])
 useEffect(()=>{restoreSession().then(s=>{setSession(s);setReady(true)}).catch(()=>setReady(true));const onStorage=e=>{if(e.key==='aeon-lang')setLangTick(x=>x+1)};window.addEventListener('storage',onStorage);const timer=setInterval(()=>setLangTick(x=>x+1),1500);return()=>{window.removeEventListener('storage',onStorage);clearInterval(timer)}},[])
 async function reload(s=session){if(!s)return;setBusy(true);try{const rows=await listDecks(s);const enriched=await Promise.all(rows.map(async d=>{try{return {...d,latest:(await analysisHistory(s,d.id,1))[0]||null}}catch{return {...d,latest:null}}}));setDecks(enriched)}catch(e){setNotice(e.message||String(e))}finally{setBusy(false)}}
 useEffect(()=>{if(session)reload(session);else setDecks([])},[session?.user?.id])
 useEffect(()=>{
   const hook=async({result,cards,commander,iterations})=>{try{const input=currentInput();if(!input.decklist||!commander?.name)return;const deckHash=await hashDeck(input.decklist,commander.name),uniq=new Map();for(const c of [...(cards||[]),commander].filter(Boolean)){const id=c.oracleId||c.id||c.name;if(!uniq.has(id))uniq.set(id,{oracleId:c.oracleId||c.id,name:c.name,oracle:c.oracle||'',type:c.type||'',tags:c.tags||[]})}const out=await recordAnalysis(session,{deckId:active?.id||null,deckName:active?.name||null,decklist:input.decklist,commanderName:commander.name,deckHash,engineVersion:ENGINE_VERSION,semanticVersion:SEMANTIC_VERSION,iterations,cards:[...uniq.values()],result});if(active&&out?.ok)reload(session)}catch(e){console.warn('Aeon cloud analysis logging failed',e)}}
   window.__AEON_ANALYSIS_HOOK__=hook;return()=>{if(window.__AEON_ANALYSIS_HOOK__===hook)delete window.__AEON_ANALYSIS_HOOK__}
 },[session?.access_token,active?.id])
 async function saveCurrent(){if(!session)return setOpen(true);const input=currentInput();if(!input.decklist||!input.commander)return setNotice(t(lang,'Paste a decklist and commander first.','Colle d’abord une decklist et un commandant.'));setBusy(true);try{const hash=await hashDeck(input.decklist,input.commander),name=(saveName||active?.name||input.commander).trim().slice(0,100),row=await saveDeck(session,{id:active?.id||null,name,commanderName:input.commander,decklist:input.decklist,deckHash:hash,engineVersion:ENGINE_VERSION});setActive(row);setSaveName(row.name);setNotice(t(lang,'Deck saved. Future analyses will be attached to its history.','Deck sauvegardé. Les prochaines analyses seront liées à son historique.'));await reload(session)}catch(e){setNotice(e.message||String(e))}finally{setBusy(false)}}
 function load(deck){nativeSet(document.getElementById('decklist'),deck.original_decklist);nativeSet(document.getElementById('commander'),deck.commander_name||deck.deck_data?.commander||'');setActive(deck);setSaveName(deck.name);setNotice(t(lang,'Deck loaded. Run a new analysis to compare it with older engine versions.','Deck chargé. Relance une analyse pour la comparer aux anciennes versions du moteur.'));setOpen(false);window.scrollTo({top:document.querySelector('.analyzerCard')?.offsetTop||0,behavior:'smooth'})}
 async function remove(deck){if(!confirm(t(lang,`Delete “${deck.name}” from your account?`,`Supprimer « ${deck.name} » de ton compte ?`)))return;setBusy(true);try{await deleteDeck(session,deck.id);if(active?.id===deck.id){setActive(null);setSaveName('')}await reload(session)}finally{setBusy(false)}}
 async function logout(){await signOut(session);setSession(null);setActive(null);setOpen(false)}
 return <>{children}<div className="cloudDock"><button className="cloudDockButton" onClick={()=>setOpen(true)}>{session?t(lang,'My decks','Mes decks'):t(lang,'Sign in','Connexion')}<span>{session?decks.length:'↗'}</span></button>{active&&<button className="cloudSaveQuick" onClick={saveCurrent} disabled={busy}>{t(lang,'Save current deck','Sauvegarder le deck')}</button>}</div>{open&&<div className="cloudBackdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><aside className="cloudDrawer"><header><div><span>AEON CLOUD</span><h2>{session?t(lang,'My decks','Mes decks'):t(lang,'Your Aeon account','Ton compte Aeon')}</h2></div><button aria-label={t(lang,'Close','Fermer')} onClick={()=>setOpen(false)}>×</button></header>{!ready?<p>{t(lang,'Loading…','Chargement…')}</p>:!session?<AuthPanel lang={lang} onDone={s=>{setSession(s);setNotice('')}}/>:<><div className="cloudAccount"><span>{session.user.email}</span><button onClick={logout}>{t(lang,'Sign out','Déconnexion')}</button></div><section className="cloudSave"><label>{t(lang,'Current deck name','Nom du deck courant')}<input value={saveName} onChange={e=>setSaveName(e.target.value)} placeholder={currentInput().commander||t(lang,'Deck name','Nom du deck')}/></label><button className="cloudPrimary" onClick={saveCurrent} disabled={busy}>{active?t(lang,'Update saved deck','Mettre à jour le deck'):t(lang,'Save current deck','Sauvegarder le deck courant')}</button>{active&&<small>{t(lang,'Loaded saved deck:','Deck sauvegardé chargé :')} {active.name}</small>}</section><div className="cloudListHead"><h3>{t(lang,'Saved decks','Decks sauvegardés')}</h3><button className="cloudLink" onClick={()=>reload()} disabled={busy}>{t(lang,'Refresh','Actualiser')}</button></div><div className="cloudDeckList">{decks.length?decks.map(d=><DeckRow key={d.id} deck={d} lang={lang} onLoad={load} onDelete={remove}/>):<p className="cloudEmpty">{t(lang,'No saved deck yet. Analyze a list, then save it here.','Aucun deck sauvegardé. Analyse une liste puis sauvegarde-la ici.')}</p>}</div></>}{notice&&<p className="cloudNotice">{notice}</p>}<footer>{t(lang,'Every analysis is versioned. Anonymous analyses also feed the semantic QA corpus; account data remains private through row-level security.','Chaque analyse est versionnée. Les analyses anonymes alimentent aussi le corpus QA sémantique ; les données de compte restent privées via les règles RLS.')}</footer></aside></div>}</>
}
