import { useEffect,useMemo,useState } from 'react'
import { analysisHistory,deckVersions,deleteDeck,deleteMyAnalysisData,hashDeck,listDecks,recordAnalysis,requestPasswordReset,restoreSession,saveDeck,saveDeckVersion,signIn,signInWithOAuth,signOut,signUp,updatePassword } from './supabaseClient.js'
import { ENGINE_VERSION,SEMANTIC_VERSION } from './version.js'

const t=(lang,en,fr)=>lang==='fr'?fr:en
const language=()=>localStorage.getItem('aeon-lang')==='fr'?'fr':'en'
const nativeSet=(el,value)=>{if(!el)return;const proto=el instanceof HTMLTextAreaElement?HTMLTextAreaElement.prototype:HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(proto,'value')?.set?.call(el,value);el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}))}
const currentInput=()=>({decklist:document.getElementById('decklist')?.value||'',commander:document.getElementById('commander')?.value||''})
const when=x=>x?new Intl.DateTimeFormat(language()==='fr'?'fr-FR':'en-US',{dateStyle:'medium',timeStyle:'short'}).format(new Date(x)):'—'
function authMessage(error,lang){
 const raw=String(error?.message||error||''),code=String(error?.code||'').toLowerCase(),s=raw.toLowerCase()
 if(code.includes('invalid_credentials')||s.includes('invalid login credentials'))return t(lang,'Incorrect email or password. Use “Forgot password?” if needed.','Email ou mot de passe incorrect. Utilise « Mot de passe oublié ? » si besoin.')
 if(code.includes('email_not_confirmed')||s.includes('email not confirmed'))return t(lang,'Your email is not confirmed yet. Open the confirmation email, then try again.','Ton e-mail n’est pas encore confirmé. Ouvre l’e-mail de confirmation puis réessaie.')
 if(code.includes('expired')||s.includes('expired')||s.includes('invalid token'))return t(lang,'This authentication link has expired. Request a new email and try again.','Ce lien de connexion a expiré. Demande un nouvel e-mail puis réessaie.')
 return raw||t(lang,'Authentication failed. Please try again.','La connexion a échoué. Réessaie.')
}

function AuthPanel({lang,onDone}){
 const[mode,setMode]=useState('signin'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
 async function submit(e){e.preventDefault();setBusy(true);setMessage('');try{
   if(mode==='forgot'){await requestPasswordReset(email);setMessage(t(lang,'If an Aeon account exists for this address, a password-reset email has been sent.','Si un compte Aeon existe pour cette adresse, un e-mail de réinitialisation vient d’être envoyé.'));return}
   if(mode==='signup'){const out=await signUp(email,password);if(out.session)onDone(out.session);else{const s=await signIn(email,password);onDone(s)}}
   else onDone(await signIn(email,password))
 }catch(e){setMessage(authMessage(e,lang))}finally{setBusy(false)}}
 const title=mode==='signup'?t(lang,'Create your Aeon account','Créer ton compte Aeon'):mode==='forgot'?t(lang,'Reset your password','Réinitialiser ton mot de passe'):t(lang,'Sign in to Aeon','Connexion à Aeon')
 return <div className="cloudAuth">
   <h3>{title}</h3>
   <p>{mode==='forgot'?t(lang,'Enter your email and Aeon will send a secure reset link.','Entre ton e-mail et Aeon enverra un lien sécurisé de réinitialisation.'):t(lang,'Save decklists, keep every analysis version and re-run them when the engine improves.','Sauvegarde tes decklists, conserve chaque version d’analyse et relance-les quand le moteur évolue.')}</p>
   {mode!=='forgot'&&<>
     <button type="button" className="cloudOAuth" onClick={()=>signInWithOAuth('google')} disabled={busy}>
       <svg width="18" height="18" viewBox="0 0 24 24" aria-hidden="true">
         <path fill="#4285F4" d="M23.745 12.27c0-.7-.06-1.4-.19-2.07H12v4.51h6.6c-.29 1.52-1.14 2.8-2.4 3.66v3.05h3.88c2.27-2.09 3.665-5.17 3.665-9.15z"/>
         <path fill="#34A853" d="M12 24c3.24 0 5.95-1.08 7.93-2.91l-3.88-3.05c-1.08.72-2.45 1.16-4.05 1.16-3.12 0-5.77-2.1-6.72-4.93H1.25v3.15C3.27 21.43 7.35 24 12 24z"/>
         <path fill="#FBBC05" d="M5.28 14.27c-.25-.72-.38-1.49-.38-2.27s.13-1.55.38-2.27V6.58H1.25C.45 8.18 0 9.99 0 12s.45 3.82 1.25 5.42l4.03-3.15z"/>
         <path fill="#EA4335" d="M12 4.75c1.77 0 3.35.61 4.6 1.8l3.42-3.42C17.95 1.19 15.24 0 12 0 7.35 0 3.27 2.57 1.25 6.58l4.03 3.15c.95-2.83 3.6-4.98 6.72-4.98z"/>
       </svg>
       <span>{t(lang,'Continue with Google','Continuer avec Google')}</span>
     </button>
     <div className="cloudAuthDivider"><span>{t(lang,'or with email','ou par e-mail')}</span></div>
   </>}
   <form onSubmit={submit}>
     <label>Email<input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label>
     {mode!=='forgot'&&<label>{t(lang,'Password','Mot de passe')}<input type="password" autoComplete={mode==='signup'?'new-password':'current-password'} minLength={6} value={password} onChange={e=>setPassword(e.target.value)} required/></label>}
     <button className="cloudPrimary" disabled={busy}>{busy?t(lang,'Please wait…','Patiente…'):mode==='signup'?t(lang,'Create account','Créer le compte'):mode==='forgot'?t(lang,'Send reset email','Envoyer l’e-mail'):t(lang,'Sign in','Se connecter')}</button>
   </form>
   {message&&<p className="cloudMessage">{message}</p>}
   {mode==='signin'&&<button className="cloudLink" onClick={()=>{setMode('forgot');setMessage('')}}>{t(lang,'Forgot password?','Mot de passe oublié ?')}</button>}
   <button className="cloudLink" onClick={()=>{setMode(mode==='signin'?'signup':'signin');setMessage('')}}>{mode==='signup'?t(lang,'Already have an account? Sign in','Déjà un compte ? Se connecter'):mode==='forgot'?t(lang,'Back to sign in','Retour à la connexion'):t(lang,'No account yet? Create one','Pas encore de compte ? En créer un')}</button>
 </div>
}

function RecoveryPanel({lang,session,onDone}){
 const[password,setPassword]=useState(''),[confirmPassword,setConfirmPassword]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
 async function submit(e){e.preventDefault();setMessage('');if(password!==confirmPassword)return setMessage(t(lang,'Passwords do not match.','Les mots de passe ne correspondent pas.'));setBusy(true);try{const next=await updatePassword(session,password);setMessage(t(lang,'Password updated. You are signed in.','Mot de passe mis à jour. Tu es connecté.'));onDone(next)}catch(e){setMessage(authMessage(e,lang))}finally{setBusy(false)}}
 return <div className="cloudAuth"><h3>{t(lang,'Choose a new password','Choisir un nouveau mot de passe')}</h3><p>{t(lang,'Your reset link is valid. Set the new password for this Aeon account.','Ton lien de réinitialisation est valide. Définis le nouveau mot de passe de ce compte Aeon.')}</p><form onSubmit={submit}><label>{t(lang,'New password','Nouveau mot de passe')}<input type="password" autoComplete="new-password" minLength={6} value={password} onChange={e=>setPassword(e.target.value)} required/></label><label>{t(lang,'Confirm password','Confirmer le mot de passe')}<input type="password" autoComplete="new-password" minLength={6} value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} required/></label><button className="cloudPrimary" disabled={busy}>{busy?t(lang,'Please wait…','Patiente…'):t(lang,'Update password','Mettre à jour le mot de passe')}</button></form>{message&&<p className="cloudMessage">{message}</p>}</div>
}

function DeckRow({deck,lang,onLoad,onDelete}){
 const h=deck.latest,history=deck.history||[],versions=deck.versions||[]
 return <article className="cloudDeck"><div><b>{deck.name}</b><span>{deck.commander_name||'Commander'}</span>{deck.source_provider&&<small>{deck.source_provider==='moxfield'?'Moxfield':'Archidekt'} · {t(lang,'linked','lié')}</small>}</div>{h?<div className="cloudDeckScore"><strong>{h.median??'—'}</strong><span>{h.p20??'—'}–{h.p80??'—'} · {t(lang,'peak','pic')} {h.peak??'—'}</span></div>:<span className="cloudNoRun">{t(lang,'Never analyzed','Jamais analysé')}</span>}<small>{h?`${h.engine_version} · ${when(h.created_at)}`:deck.latest_analysis_at?when(deck.latest_analysis_at):t(lang,'Saved decklist','Decklist sauvegardée')}</small>{history.length>0&&<details className="cloudHistory" style={{gridColumn:'1 / -1'}}><summary>{t(lang,`Analysis history (${history.length})`,`Historique des analyses (${history.length})`)}</summary><div className="cloudHistoryList">{history.map(run=><div className="cloudHistoryRun" key={run.id}><div><b>v{run.engine_version}</b><span>{when(run.created_at)}</span></div><div><strong>{run.median??'—'}</strong><span>P20 {run.p20??'—'} · P80 {run.p80??'—'} · {t(lang,'peak','pic')} {run.peak??'—'}</span></div></div>)}</div></details>}{versions.length>1&&<details className="cloudHistory" style={{gridColumn:'1 / -1'}}><summary>{t(lang,`Decklist versions (${versions.length})`,`Versions de decklist (${versions.length})`)}</summary><div className="cloudHistoryList">{versions.slice(0,8).map(v=><div className="cloudHistoryRun" key={v.id}><div><b>{v.source_provider||t(lang,'Manual','Manuel')}</b><span>{when(v.created_at)}</span></div><div><span>{String(v.deck_hash||'').slice(0,10)}…</span></div></div>)}</div></details>}<div className="cloudDeckActions"><button onClick={()=>onLoad(deck)}>{t(lang,'Load & re-analyze','Charger & réanalyser')}</button><button className="danger" onClick={()=>onDelete(deck)}>{t(lang,'Delete','Supprimer')}</button></div></article>
}

export default function CloudWorkspace({children}){
 const[session,setSession]=useState(null),[ready,setReady]=useState(false),[open,setOpen]=useState(false),[decks,setDecks]=useState([]),[busy,setBusy]=useState(false),[active,setActive]=useState(null),[saveName,setSaveName]=useState(''),[notice,setNotice]=useState(''),[langTick,setLangTick]=useState(0),[sourceMeta,setSourceMeta]=useState(null),[recovery,setRecovery]=useState(false)
 const lang=useMemo(()=>{langTick;return language()},[langTick])
 useEffect(()=>{restoreSession().then(s=>{setSession(s);if(s?.authEvent==='recovery'){setRecovery(true);setOpen(true)}else if(s?.authEvent){setNotice(t(language(),'Email confirmed. You are signed in.','E-mail confirmé. Tu es connecté.'));setOpen(true)}setReady(true)}).catch(e=>{setNotice(authMessage(e,language()));setOpen(true);setReady(true)});const onStorage=e=>{if(e.key==='aeon-lang')setLangTick(x=>x+1)},onImport=e=>setSourceMeta(e.detail||null);window.addEventListener('storage',onStorage);window.addEventListener('aeon-deck-imported',onImport);const timer=setInterval(()=>setLangTick(x=>x+1),1500);return()=>{window.removeEventListener('storage',onStorage);window.removeEventListener('aeon-deck-imported',onImport);clearInterval(timer)}},[])
 async function reload(s=session){if(!s)return;setBusy(true);try{const rows=await listDecks(s);const enriched=await Promise.all(rows.map(async d=>{const [history,versions]=await Promise.all([analysisHistory(s,d.id,8).catch(()=>[]),deckVersions(s,d.id,12).catch(()=>[])]);return {...d,history,versions,latest:history[0]||null}}));setDecks(enriched)}catch(e){setNotice(e.message||String(e))}finally{setBusy(false)}}
 useEffect(()=>{if(session)reload(session);else setDecks([])},[session?.user?.id])
 useEffect(()=>{
   const hook=async({result,cards,commander,iterations})=>{try{const input=currentInput();if(!input.decklist||!commander?.name)return;const deckHash=await hashDeck(input.decklist,commander.name),uniq=new Map();for(const c of [...(cards||[]),commander].filter(Boolean)){const id=c.oracleId||c.id||c.name;if(!uniq.has(id))uniq.set(id,{oracleId:c.oracleId||c.id,scryfallId:c.scryfallId||c.id||null,name:c.name,oracle:c.oracle||'',type:c.type||'',tags:c.tags||[]})}const out=await recordAnalysis(session,{deckId:active?.id||null,deckName:active?.name||sourceMeta?.deckName||null,decklist:input.decklist,commanderName:commander.name,deckHash,engineVersion:ENGINE_VERSION,semanticVersion:SEMANTIC_VERSION,iterations,cards:[...uniq.values()],result});if(active&&out?.ok)reload(session)}catch(e){console.warn('Aeon cloud analysis logging failed',e)}}
   window.__AEON_ANALYSIS_HOOK__=hook;return()=>{if(window.__AEON_ANALYSIS_HOOK__===hook)delete window.__AEON_ANALYSIS_HOOK__}
 },[session?.access_token,active?.id,active?.name,sourceMeta?.deckName])
 async function saveCurrent(){if(!session)return setOpen(true);const input=currentInput();if(!input.decklist||!input.commander)return setNotice(t(lang,'Paste a decklist and commander first.','Colle d’abord une decklist et un commandant.'));setBusy(true);try{const hash=await hashDeck(input.decklist,input.commander),name=(saveName||active?.name||sourceMeta?.deckName||input.commander).trim().slice(0,100),row=await saveDeck(session,{id:active?.id||null,name,commanderName:input.commander,decklist:input.decklist,deckHash:hash,engineVersion:ENGINE_VERSION,sourceUrl:sourceMeta?.sourceUrl||active?.source_url||null,sourceProvider:sourceMeta?.source||active?.source_provider||null,sourceDeckId:sourceMeta?.sourceId||active?.source_deck_id||null,sourceTitle:sourceMeta?.deckName||active?.source_title||null,sourceFingerprint:sourceMeta?.sourceFingerprint||hash});await saveDeckVersion(session,{deckId:row.id,deckHash:hash,commanderNames:[input.commander],decklist:input.decklist,sourceProvider:sourceMeta?.source||row.source_provider||null,sourceUrl:sourceMeta?.sourceUrl||row.source_url||null,sourceFingerprint:sourceMeta?.sourceFingerprint||hash});setActive(row);setSaveName(row.name);setNotice(t(lang,'Deck saved and versioned. Future analyses will be attached to its history.','Deck sauvegardé et versionné. Les prochaines analyses seront liées à son historique.'));await reload(session)}catch(e){setNotice(e.message||String(e))}finally{setBusy(false)}}
 function load(deck){nativeSet(document.getElementById('decklist'),deck.original_decklist);nativeSet(document.getElementById('commander'),deck.commander_name||deck.deck_data?.commander||'');setActive(deck);setSaveName(deck.name);const source=deck.source_url?{source:deck.source_provider,sourceUrl:deck.source_url,sourceId:deck.source_deck_id,deckName:deck.source_title||deck.name,decklist:deck.original_decklist,commanderName:deck.commander_name,sourceFingerprint:deck.source_fingerprint}:null;setSourceMeta(source);if(source)window.dispatchEvent(new CustomEvent('aeon-deck-imported',{detail:source}));setNotice(t(lang,'Deck loaded. Run a new analysis to compare it with older engine versions.','Deck chargé. Relance une analyse pour la comparer aux anciennes versions du moteur.'));setOpen(false);window.scrollTo({top:document.querySelector('.analyzerCard')?.offsetTop||0,behavior:'smooth'})}
 async function remove(deck){if(!confirm(t(lang,`Delete “${deck.name}” and its linked analysis history from your account?`,`Supprimer « ${deck.name} » et son historique d’analyses lié de ton compte ?`)))return;setBusy(true);try{await deleteDeck(session,deck.id);if(active?.id===deck.id){setActive(null);setSaveName('')}await reload(session)}finally{setBusy(false)}}
 async function eraseHistory(){if(!confirm(t(lang,'Delete every analysis stored for this account? Saved decklists will remain. This cannot be undone.','Supprimer toutes les analyses stockées pour ce compte ? Les decklists sauvegardées resteront. Cette action est irréversible.')))return;setBusy(true);try{const count=await deleteMyAnalysisData(session);setNotice(t(lang,`${Number(count)||0} stored analyses deleted. Your saved decklists remain.`,`${Number(count)||0} analyses stockées supprimées. Tes decklists sauvegardées restent.`));await reload(session)}catch(e){setNotice(e.message||String(e))}finally{setBusy(false)}}
 async function logout(){await signOut(session);setSession(null);setRecovery(false);setActive(null);setOpen(false)}
 return <>{children}<div className="cloudDock"><button className="cloudDockButton" onClick={()=>setOpen(true)}>{session?t(lang,'My decks','Mes decks'):t(lang,'Sign in','Connexion')}<span>{session?decks.length:'↗'}</span></button>{active&&<button className="cloudSaveQuick" onClick={saveCurrent} disabled={busy}>{t(lang,'Save current deck','Sauvegarder le deck')}</button>}</div>{open&&<div className="cloudBackdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><aside className="cloudDrawer"><header><div><span>AEON CLOUD</span><h2>{session?t(lang,'My decks','Mes decks'):t(lang,'Your Aeon account','Ton compte Aeon')}</h2></div><button aria-label={t(lang,'Close','Fermer')} onClick={()=>setOpen(false)}>×</button></header>{!ready?<p>{t(lang,'Loading…','Chargement…')}</p>:!session?<AuthPanel lang={lang} onDone={s=>{setSession(s);setRecovery(false);setNotice('')}}/>:recovery?<RecoveryPanel lang={lang} session={session} onDone={s=>{setSession(s);setRecovery(false);setNotice(t(lang,'Password updated. Your Aeon session is active.','Mot de passe mis à jour. Ta session Aeon est active.'))}}/>:<><div className="cloudAccount"><span>{session.user.email}</span><button onClick={logout}>{t(lang,'Sign out','Déconnexion')}</button></div><section className="cloudSave"><label>{t(lang,'Current deck name','Nom du deck courant')}<input value={saveName} onChange={e=>setSaveName(e.target.value)} placeholder={currentInput().commander||t(lang,'Deck name','Nom du deck')}/></label><button className="cloudPrimary" onClick={saveCurrent} disabled={busy}>{active?t(lang,'Update saved deck','Mettre à jour le deck'):t(lang,'Save current deck','Sauvegarder le deck courant')}</button>{active&&<small>{t(lang,'Loaded saved deck:','Deck sauvegardé chargé :')} {active.name}</small>}</section><div className="cloudListHead"><h3>{t(lang,'Saved decks','Decks sauvegardés')}</h3><button className="cloudLink" onClick={()=>reload()} disabled={busy}>{t(lang,'Refresh','Actualiser')}</button></div><div className="cloudDeckList">{decks.length?decks.map(d=><DeckRow key={d.id} deck={d} lang={lang} onLoad={load} onDelete={remove}/>):<p className="cloudEmpty">{t(lang,'No saved deck yet. Analyze a list, then save it here.','Aucun deck sauvegardé. Analyse une liste puis sauvegarde-la ici.')}</p>}</div><div style={{borderTop:'1px solid #292732',marginTop:18,paddingTop:10}}><button className="cloudLink" style={{color:'#d89aa5'}} onClick={eraseHistory} disabled={busy}>{t(lang,'Delete my analysis history','Supprimer mon historique d’analyses')}</button></div></>}{notice&&<p className="cloudNotice">{notice}</p>}<footer>{t(lang,'Every analysis and decklist version is versioned. Anonymous analyses also feed semantic QA; you can erase all account-linked analysis history at any time.','Chaque analyse et version de decklist est versionnée. Les analyses anonymes alimentent aussi la QA sémantique ; tu peux effacer à tout moment tout l’historique d’analyses lié à ton compte.')}</footer></aside></div>}</>
}
