import { useState } from 'react'
import './deckImport.css'

const t=(lang,en,fr)=>lang==='fr'?fr:en

export default function DeckImportPanel({lang='en',onImported}){
  const[url,setUrl]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState('')
  const L=(en,fr)=>t(lang,en,fr)
  async function submit(ev){ev?.preventDefault?.();if(!url.trim()||busy)return;setBusy(true);setNotice('');setError('');try{const response=await fetch('/api/import-deck',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:url.trim()})}),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||L('Unable to import this deck.','Impossible d’importer ce deck.'));if(!data.commanderName||!data.decklist)throw new Error(L('The imported deck is missing a usable command zone or main deck.','Le deck importé ne contient pas de zone de commandement ou de deck principal exploitable.'));onImported?.(data);if(typeof window!=='undefined'&&typeof CustomEvent!=='undefined')window.dispatchEvent(new CustomEvent('aeon-deck-imported',{detail:data}));const source=data.source==='moxfield'?'Moxfield':'Archidekt',commanders=(data.commanderNames||[data.commanderName]).filter(Boolean);setNotice(L(`${source} imported · ${data.cardCount} main-deck cards · ${commanders.join(' + ')}`,`${source} importé · ${data.cardCount} cartes dans le deck · ${commanders.join(' + ')}`))}catch(e){setError(e.message||String(e))}finally{setBusy(false)}}
  return <section className="deckUrlImport" aria-labelledby="deck-url-import-label"><div className="deckUrlImportHead"><div><span className="sectionEyebrow">{L('QUICK IMPORT','IMPORT RAPIDE')}</span><label id="deck-url-import-label" htmlFor="deck-url">{L('Moxfield or Archidekt link','Lien Moxfield ou Archidekt')}</label></div><span>{L('Public decks','Decks publics')}</span></div><form className="deckUrlImportRow" onSubmit={submit}><input id="deck-url" type="url" inputMode="url" autoComplete="off" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://www.moxfield.com/decks/…  ·  https://archidekt.com/decks/…"/><button type="submit" disabled={busy||!url.trim()}>{busy?L('Importing…','Import…'):L('Import deck','Importer')}</button></form><p>{L('Aeon reads the public source and fills the command zone plus the main deck below. One- and two-card command zones can be imported; you can still edit everything before analysis.','Aeon lit la source publique puis remplit la zone de commandement et le deck principal ci-dessous. Les zones de commandement à une ou deux cartes peuvent être importées ; tu peux encore tout modifier avant l’analyse.')}</p>{notice&&<div className="deckImportNotice" role="status">✓ {notice}</div>}{error&&<div className="deckImportError" role="alert"><b>{L('Import failed','Import impossible')}</b><span>{error}</span><small>{L('If the source site is temporarily unavailable, retrying a little later is enough; Aeon now distinguishes that case from an invalid deck link.','Si le site source est temporairement indisponible, il suffit de réessayer un peu plus tard ; Aeon distingue désormais ce cas d’un lien de deck invalide.')}</small></div>}</section>
}
