import { useState } from 'react'
import { submitGameObservation } from './supabaseClient.js'

const lang=()=>localStorage.getItem('aeon-lang')==='fr'?'fr':'en'
const t=(en,fr)=>lang()==='fr'?fr:en
export default function GameObservationForm({rows=[],podModelVersion='pod-intelligence-v1',prediction={}}){
  const[turnBand,setTurnBand]=useState('5-7'),[winType,setWinType]=useState('combat'),[balance,setBalance]=useState('balanced'),[dominantEvent,setDominantEvent]=useState('normal-game'),[state,setState]=useState(''),[busy,setBusy]=useState(false)
  async function submit(){setBusy(true);setState('');try{await submitGameObservation({shareCodes:rows.map(r=>r.share_code).filter(Boolean),podModelVersion,engineVersions:rows.map(r=>r.engine_version).filter(Boolean),semanticVersions:rows.map(r=>r.semantic_version).filter(Boolean),prediction,turnBand,winType,balance,dominantEvent});setState(t('Observation recorded. Thank you.','Observation enregistrée. Merci.'))}catch(e){setState(e.message||String(e))}finally{setBusy(false)}}
  return <details className="whatIf"><summary>{t('After the game · help validate Aeon','Après la partie · aider à valider Aeon')}</summary><p className="productNote">{t('Optional observational feedback. Aeon stores the pre-game aggregate prediction with your outcome so the model can later be tested honestly. No decklist, card list or Oracle text is stored, and feedback never rewrites semantic truth automatically.','Retour observationnel facultatif. Aeon stocke la prédiction agrégée pré-game avec le résultat afin de pouvoir tester honnêtement le modèle plus tard. Aucune decklist, liste de cartes ou texte Oracle n’est stocké, et le retour ne réécrit jamais automatiquement la vérité sémantique.')}</p><div className="feedbackBox"><select value={turnBand} onChange={e=>setTurnBand(e.target.value)}><option value="1-4">T1–4</option><option value="5-7">T5–7</option><option value="8-10">T8–10</option><option value="11+">T11+</option></select><select value={winType} onChange={e=>setWinType(e.target.value)}><option value="combat">{t('Combat','Combat')}</option><option value="combo">Combo</option><option value="drain">Drain</option><option value="lock">Lock</option><option value="concession">{t('Concession','Concession')}</option><option value="other">{t('Other','Autre')}</option></select><select value={balance} onChange={e=>setBalance(e.target.value)}><option value="very-unbalanced">{t('Very unbalanced','Très déséquilibrée')}</option><option value="unbalanced">{t('Unbalanced','Déséquilibrée')}</option><option value="mixed">{t('Mixed','Mitigée')}</option><option value="balanced">{t('Balanced','Équilibrée')}</option><option value="very-balanced">{t('Very balanced','Très équilibrée')}</option></select><select value={dominantEvent} onChange={e=>setDominantEvent(e.target.value)}><option value="normal-game">{t('Normal game','Partie normale')}</option><option value="runaway-start">{t('Runaway start','Départ incontrôlé')}</option><option value="unanswered-combo">{t('Unanswered combo','Combo sans réponse')}</option><option value="lock">Lock</option><option value="mana-issue">{t('Mana issue','Problème de mana')}</option><option value="other">{t('Other','Autre')}</option><option value="none">{t('None','Aucun')}</option></select><button onClick={submit} disabled={busy}>{busy?t('Sending…','Envoi…'):t('Record observation','Enregistrer')}</button></div>{state&&<p className="productNote">{state}</p>}</details>
}
