import { useEffect,useState } from 'react'
import { AEON_LABEL,SEMANTIC_VERSION } from './version.js'

const language=()=>localStorage.getItem('aeon-lang')==='fr'?'fr':'en'
const SITE='https://aeon-scorer.vercel.app'
const t=(lang,en,fr)=>lang==='fr'?fr:en
const ROUTE_META={
  '/decklists-publiques':{en:['Official Commander precons — Aeon Scorer','Browse current Aeon analyses of official Commander preconstructed decks.'],fr:['Préconstruits Commander — Aeon Scorer','Parcours les analyses Aeon à jour des préconstruits Commander officiels.']},
  '/pod':{en:['Compare 2–4 Commander decks — Aeon Scorer','Cross-evaluate two to four versioned Aeon deck analyses before a Commander game.'],fr:['Comparer 2–4 decks Commander — Aeon Scorer','Évalue ensemble deux à quatre analyses Aeon versionnées avant une partie Commander.']},
  '/match':{en:['Build balanced Commander tables — Aeon Scorer','Form Commander tables of four from a player pool using Aeon compatibility diagnostics.'],fr:['Former des tables Commander équilibrées — Aeon Scorer','Forme des tables Commander de quatre à partir d’un groupe de joueurs avec les diagnostics de compatibilité Aeon.']},
  '/tournoi':{en:['Commander tournament bracket — Aeon Scorer','Create a duel or four-player Commander tournament bracket.'],fr:['Arbre de tournoi Commander — Aeon Scorer','Crée un arbre de tournoi Commander en duel ou par tables de quatre.']},
}
function basePath(){const p=location.pathname;return p.startsWith('/a/')?'/a':p}
function setMeta(lang){
  const key=basePath(),fallback=key==='/a'?{en:['Shared deck analysis — Aeon Scorer','A versioned Aeon Commander deck analysis shared for pre-game discussion.'],fr:['Analyse de deck partagée — Aeon Scorer','Une analyse Commander Aeon versionnée partagée pour la discussion avant partie.']}:null,meta=(ROUTE_META[key]||fallback)?.[lang]
  if(!meta)return
  document.documentElement.lang=lang;document.title=meta[0]
  const desc=document.querySelector('meta[name="description"]');if(desc)desc.setAttribute('content',meta[1])
  let canonical=document.querySelector('link[rel="canonical"]');if(!canonical){canonical=document.createElement('link');canonical.rel='canonical';document.head.appendChild(canonical)}canonical.href=`${SITE}${location.pathname}`
  document.querySelector('meta[property="og:title"]')?.setAttribute('content',meta[0]);document.querySelector('meta[property="og:description"]')?.setAttribute('content',meta[1]);document.querySelector('meta[property="og:url"]')?.setAttribute('content',canonical.href)
}
function Nav({lang,onLanguage}){const path=location.pathname;const active=href=>href==='/'?path==='/' : path===href||path.startsWith(`${href}/`);return <div className="navFrame globalRouteNav"><nav className="siteNav" aria-label={t(lang,'Main navigation','Navigation principale')}>
  <a href="/" className="brand"><span className="brandMark" aria-hidden="true"><i>A</i></span><span className="brandText"><b>Aeon Scorer</b><small>{t(lang,'Commander power analyzer','Analyseur de puissance Commander')}</small></span></a>
  <div className="navLinks globalProductLinks"><a className={active('/')?'active':''} href="/">{t(lang,'Analyze','Analyser')}</a><a className={active('/decklists-publiques')?'active':''} href="/decklists-publiques">{t(lang,'Precons','Préconstruits')}</a><a className={active('/pod')?'active':''} href="/pod">{t(lang,'Compare 2–4','Comparer 2–4')}</a><a className={active('/match')?'active':''} href="/match">{t(lang,'Tables of 4','Tables de 4')}</a><a className={active('/tournoi')?'active':''} href="/tournoi">{t(lang,'Tournament','Tournoi')}</a></div>
  <div className="navActions"><div className="languageSwitch" role="group" aria-label={t(lang,'Language','Langue')}><button className={lang==='en'?'active':''} onClick={()=>onLanguage('en')}>EN</button><button className={lang==='fr'?'active':''} onClick={()=>onLanguage('fr')}>FR</button></div></div>
</nav></div>}
function PreconReference({lang}){const[stats,setStats]=useState(null);useEffect(()=>{let dead=false;fetch('/api/precon-stats').then(r=>r.ok?r.json():null).then(x=>{if(x&&!dead)setStats(x)}).catch(()=>{});return()=>{dead=true}},[]);if(!stats)return null;return <section className="preconReference" aria-label={t(lang,'Current precon reference','Référence préconstruits actuelle')}><div><span>{t(lang,'CURRENT PUBLIC DATASET','JEU DE DONNÉES PUBLIC ACTUEL')}</span><b>{stats.analyzed}/{stats.total} {t(lang,'precons analyzed','préconstruits analysés')}</b><small>{stats.sourceName} · {stats.sourceRevision||'—'} · Aeon {stats.engineVersion} / {stats.semanticVersion}</small></div><div className="preconReferenceStats"><span><b>{stats.reference?.median??'—'}</b><small>{t(lang,'median deck score','médiane des scores')}</small></span><span><b>{stats.reference?.mean??'—'}</b><small>{t(lang,'mean deck score','moyenne des scores')}</small></span><span><b>{stats.unsupported}</b><small>{t(lang,'not yet analyzable','non analysables')}</small></span></div><p>{t(lang,'This reference is calculated from the currently supported public catalog, not from a hard-coded historical number.','Cette référence est calculée sur le catalogue public actuellement pris en charge, pas à partir d’un ancien chiffre codé en dur.')}</p></section>}
function Footer({lang}){return <footer className="globalProductFooter"><div><b>Aeon Scorer {AEON_LABEL}</b><span>{t(lang,'Product version','Version produit')} · {t(lang,'semantic model','modèle sémantique')} {SEMANTIC_VERSION}</span></div><nav><a href="/decklists-publiques">{t(lang,'Precons','Préconstruits')}</a><a href="/pod">{t(lang,'Compare','Comparer')}</a><a href="/match">{t(lang,'Tables','Tables')}</a><a href="/tournoi">{t(lang,'Tournament','Tournoi')}</a><a href="/methodologie">{t(lang,'Methodology','Méthodologie')}</a></nav></footer>}
export default function GlobalProductChrome({children}){const[lang,setLang]=useState(language());useEffect(()=>setMeta(lang),[lang]);function change(next){if(next===lang)return;localStorage.setItem('aeon-lang',next);setLang(next);location.reload()}return <div className="globalProductShell"><Nav lang={lang} onLanguage={change}/>{location.pathname.startsWith('/decklists-publiques')&&<PreconReference lang={lang}/>}<div className="globalProductBody">{children}</div><Footer lang={lang}/></div>}
