import { useEffect,useMemo,useState } from 'react'
import { createPortal } from 'react-dom'
import Rule0Tools from './Rule0Tools.jsx'
import MultiCommanderControls from './MultiCommanderControls.jsx'
import CardSemanticAudit from './CardSemanticAudit.jsx'
import { deckDiff,localBracketSignals } from './productData.js'
import { buildDeckIntelligence,buildShareableIntelligence } from './engine/roadmapEngine.js'
import { createAnalysisShare } from './supabaseClient.js'
import { FriendlyCopyObserver,ResultActionBar,WorkflowNav,usePortalTarget } from './UxEnhancements.jsx'
import { metricLabel,methodLabel,levelLabel } from './uxCopy.js'
import './product.css'

const currentInput=()=>({decklist:document.getElementById('decklist')?.value||'',commander:document.getElementById('commander')?.value||''})
const nativeSet=(el,value)=>{if(!el)return;const proto=el instanceof HTMLTextAreaElement?HTMLTextAreaElement.prototype:HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(proto,'value')?.set?.call(el,value);el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}))}
const language=()=>localStorage.getItem('aeon-lang')==='fr'?'fr':'en'
const t=(en,fr)=>language()==='fr'?fr:en
const human=s=>String(s||'').replace(/([a-z])([A-Z])/g,'$1 $2').replace(/[-_]/g,' ').trim()
const suppressionImpact=n=>{const x=Number(n)||0;return `${x>=0?'−':'+'}${Math.abs(x)}`}

function SourceSync({source,onSource}){
  const[fresh,setFresh]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('')
  const current=currentInput(),diff=useMemo(()=>fresh?deckDiff(current.decklist,fresh.decklist):null,[fresh,current.decklist])
  if(!source?.sourceUrl)return null
  async function refresh(){setBusy(true);setError('');setFresh(null);try{const r=await fetch('/api/import-deck',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:source.sourceUrl})}),x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(x.error||t('Source refresh failed.','Impossible de vérifier la source.'));setFresh(x)}catch(e){setError(e.message||String(e))}finally{setBusy(false)}}
  function load(){if(!fresh)return;nativeSet(document.getElementById('decklist'),fresh.decklist||'');nativeSet(document.getElementById('commander'),fresh.commanderName||'');onSource?.(fresh);window.dispatchEvent(new CustomEvent('aeon-deck-imported',{detail:fresh}));window.scrollTo({top:document.querySelector('.analyzerCard')?.offsetTop||0,behavior:'smooth'})}
  const sourceName=source.source==='moxfield'?'Moxfield':'Archidekt'
  return <section className="sourceSyncCard"><div><span>{t('DECK SOURCE','SOURCE DU DECK')}</span><b>{sourceName}</b><small>{t('The current analysis stays frozen until you explicitly load an updated source list.','L’analyse actuelle reste figée tant que tu ne charges pas explicitement une nouvelle version de la liste.')}</small></div><div className="sourceSyncActions"><a href={source.sourceUrl} target="_blank" rel="noreferrer">{t('Open source ↗','Ouvrir la source ↗')}</a><button onClick={refresh} disabled={busy}>{busy?t('Checking…','Vérification…'):t('Check for updates','Vérifier les mises à jour')}</button></div>{error&&<div className="productError">{error}</div>}{fresh&&<div className="sourceSyncDiff">{diff?.changes?<><div className="deckDiff"><div><b>+ {t('Added upstream','Ajouté sur la source')}</b><ul>{diff.added.slice(0,14).map(x=><li key={x.name}>{x.qty} {x.name}</li>)}</ul></div><div><b>− {t('Removed upstream','Retiré sur la source')}</b><ul>{diff.removed.slice(0,14).map(x=><li key={x.name}>{x.qty} {x.name}</li>)}</ul></div></div><button className="productPrimary" onClick={load}>{t('Load this updated version','Charger cette nouvelle version')}</button></>:<div className="deckImportNotice">✓ {t('No source change detected.','Aucun changement détecté sur la source.')}</div>}</div>}</section>
}

function SuppressionStress({spof,lang}){
  const rows=Object.entries(spof?.dependencySuppression?.scenarios||{}).filter(([,x])=>x?.status==='paired').sort((a,b)=>Math.abs(Number(b[1]?.delta?.median||0))-Math.abs(Number(a[1]?.delta?.median||0))||a[0].localeCompare(b[0]))
  if(!rows.length)return null
  return <details className="aeonLabSection"><summary><span><b>{t('Dependency stress test','Test de résistance des dépendances')}</b><small>{spof.dependencySuppression.iterations} {t('sequences per scenario','séquences par scénario')}</small></span><i>+</i></summary><div className="labSectionBody"><p>{t('Aeon temporarily neutralizes cards contributing to one dependency while preserving deck size and seed. This is a diagnostic counterfactual, not a literal simulation of a specific hate card.','Aeon neutralise temporairement les cartes qui contribuent à une dépendance en conservant la taille du deck et la seed. C’est un contrefactuel diagnostique, pas la simulation littérale d’une carte de hate précise.')}</p><div className="insightGrid">{rows.map(([kind,x])=><div className="insightCard" key={kind}><b>{metricLabel(kind,lang)}</b><p>{t('Median impact','Impact sur la médiane')} · <strong>{suppressionImpact(x.delta?.median)}</strong></p><p>{t('Peak impact','Impact sur le pic')} · <strong>{suppressionImpact(x.delta?.peak)}</strong></p><small>{x.suppressedCards} {t('contributing card(s) neutralized','carte(s) contributrice(s) neutralisée(s)')} · {t('engine access','accès moteur')} T4 {suppressionImpact(x.delta?.engineT4)} · T5 {suppressionImpact(x.delta?.engineT5)}</small></div>)}</div></div></details>
}

function ComboTiming({comboAccessibility,lang}){
  const lines=comboAccessibility?.lines||[]
  if(!lines.length)return null
  return <details className="aeonLabSection"><summary><span><b>{t('Combo-piece access','Accès aux pièces de combo')}</b><small>{comboAccessibility.timing?.supportedLines||0}/{comboAccessibility.timing?.totalLines||lines.length} {t('lines with temporal evidence','lignes avec preuve temporelle')}</small></span><i>+</i></summary><div className="labSectionBody"><p>{t('T5/T7/T9 measure raw presence of every required library piece in the opening seven plus one raw draw per turn. They are not execution or win probabilities.','T5/T7/T9 mesurent la présence brute de toutes les pièces nécessaires en bibliothèque dans les sept cartes initiales + une pioche brute par tour. Ce ne sont ni des probabilités d’exécution ni de victoire.')}</p><div className="insightGrid">{lines.map((line,i)=>{const timing=line.timing||{},eligibility=line.executionEligibility||{},supported=timing.status==='piece-presence-supported',blockers=eligibility.blockers||[];return <div className="insightCard" key={`${line.name||'combo'}-${i}`}><b>{line.name||t('Detected combo','Combo détectée')}</b>{supported?<><p>{(timing.windows||[]).map(w=>`T${w.turn} ${w.piecePresence}%`).join(' · ')}</p><small>{timing.libraryPieces} {t('library piece(s)','pièce(s) bibliothèque')} · {timing.commandZonePieces} {t('command-zone piece(s)','pièce(s) en zone de commandement')}</small></>:<><p>{t('Temporal evidence unavailable','Preuve temporelle indisponible')}</p><small>{(timing.unsupportedReasons||[]).map(human).join(' · ')||t('Prerequisites cannot be represented reliably.','Les prérequis ne peuvent pas être représentés de façon fiable.')}</small></>}{eligibility.modelVersion&&<p><strong>{t('Execution prerequisites','Prérequis d’exécution')}</strong> · {blockers.length?t(`${blockers.length} unproven strict prerequisite(s)`,`${blockers.length} prérequis strict(s) non prouvé(s)`):t('required evidence represented; exact timing still not claimed','preuves requises représentées ; aucun timing exact revendiqué')}</p>}</div>})}</div></div></details>
}

function IntelligenceGlossary({intel,lang}){
  const highest=intel?.spof?.highest
  return <details className="aeonLabSection"><summary><span><b>{t('How to read the experimental metrics','Comment lire les métriques expérimentales')}</b><small>{t('Terminology and evidence level','Terminologie et niveau de preuve')}</small></span><i>+</i></summary><div className="labSectionBody"><div className="labGlossary"><p><b>{t('Critical dependency','Dépendance critique')}</b> — {t('A structural reliance measured independently from the main 0–100 score.','Une dépendance structurelle mesurée séparément du score principal 0–100.')}</p><p><b>{t('Unopposed speed','Vitesse sans opposition')}</b> — {t('First-access milestones in goldfish conditions; not a full game probability.','Des jalons de premier accès sans opposition ; pas une probabilité de partie complète.')}</p><p><b>{t('Participation capacity','Capacité à participer')}</b> — {t('A diagnostic of whether a deck has meaningful actions before opposing pressure arrives.','Un diagnostic indiquant si un deck dispose d’actions significatives avant l’arrivée de la pression adverse.')}</p>{highest&&<p><b>{t('Highest current dependency','Dépendance actuelle la plus forte')}</b> — {metricLabel(highest.kind,lang)} · {levelLabel(highest.level,lang)}{methodLabel(highest.method,lang)?` · ${methodLabel(highest.method,lang)}`:''}</p>}</div></div></details>
}

export default function ProductWorkspace({children}){
  const[analysis,setAnalysis]=useState(null),[analysisId,setAnalysisId]=useState(null),[source,setSource]=useState(null),[insights,setInsights]=useState(null),[shareCode,setShareCode]=useState(''),[shareBusy,setShareBusy]=useState(false),[langTick,setLangTick]=useState(0)
  useEffect(()=>{
    const computed=e=>{const input=currentInput();setAnalysis({...e.detail,decklist:input.decklist,commanderNames:(e.detail?.commanders?.length?e.detail.commanders.map(c=>c.name):[e.detail?.commander?.name||input.commander]).filter(Boolean)});setAnalysisId(null);setShareCode('');setInsights(null)}
    const recorded=e=>{const out=e.detail||{},id=out?.analysis?.id||out?.id||null;if(id)setAnalysisId(id)}
    const imported=e=>setSource(e.detail||null)
    const storage=e=>{if(e.key==='aeon-lang')setLangTick(x=>x+1)}
    window.addEventListener('aeon-analysis-computed',computed);window.addEventListener('aeon-analysis-recorded',recorded);window.addEventListener('aeon-deck-imported',imported);window.addEventListener('storage',storage)
    return()=>{window.removeEventListener('aeon-analysis-computed',computed);window.removeEventListener('aeon-analysis-recorded',recorded);window.removeEventListener('aeon-deck-imported',imported);window.removeEventListener('storage',storage)}
  },[])
  const lang=useMemo(()=>{langTick;return language()},[langTick]),localCards=useMemo(()=>analysis?[...(analysis.cards||[]),...((analysis.commanders?.length?analysis.commanders:[analysis.commander]).filter(Boolean))]:[],[analysis]),localIntelligence=useMemo(()=>analysis?.result?buildDeckIntelligence(analysis.result,localCards):null,[analysis,localCards])
  useEffect(()=>{let dead=false;if(!analysis?.decklist||!analysis?.commanderNames?.length){setInsights(null);return}fetch('/api/commander-insights',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({decklist:analysis.decklist,commanders:analysis.commanderNames})}).then(async r=>{const x=await r.json().catch(()=>({}));if(r.ok&&!dead)setInsights(x)}).catch(()=>{});return()=>{dead=true}},[analysis?.decklist,analysis?.commanderNames?.join('|')])
  const sourceTarget=usePortalTarget('.deckUrlImport',{className:'sourceSyncHost',placement:'after'}),labTarget=usePortalTarget('.resultsArea',{className:'aeonLabHost',placement:'after'})
  async function ensureShare(){if(shareCode)return shareCode;if(!analysisId)throw new Error(t('The analysis is still being versioned. Try again in a moment.','L’analyse est encore en cours de versionnage. Réessaie dans un instant.'));setShareBusy(true);try{const signals=localBracketSignals(localCards,analysis.result,insights),productIntelligence=buildShareableIntelligence(analysis.result,localCards),code=await createAnalysisShare(analysisId,{gameChangers:signals.gameChangers,bracketSignals:{...signals,spellbookBracket:insights?.bracketTag||null,twoCardCombos:insights?.twoCardCombos||signals.twoCardCombos},comboSummary:insights?.included||analysis.result?.combos||[],productIntelligence});setShareCode(code);return code}finally{setShareBusy(false)}}
  async function share(){const code=await ensureShare(),url=`${location.origin}/a/${code}`;if(navigator.share){try{await navigator.share({title:analysis?.commanderNames?.join(' + ')||'Aeon Scorer',url});return url}catch{}}await navigator.clipboard?.writeText(url);return url}
  async function compare(){const code=await ensureShare();location.href=`/pod?d=${code}`}
  async function tables(){const code=await ensureShare();sessionStorage.setItem('aeon-seed-share',code);location.href=`/match?d=${code}`}
  async function tournament(){const code=await ensureShare();location.href=`/tournoi?d=${code}`}
  const shareUrl=shareCode?`${location.origin}/a/${shareCode}`:''
  return <><FriendlyCopyObserver/><WorkflowNav/>{children}<MultiCommanderControls source={source}/>{analysis?.result&&<ResultActionBar analysisReady={!!analysisId} shareBusy={shareBusy} shareUrl={shareUrl} onShare={share} onCompare={compare} onTables={tables} onTournament={tournament}/>} {sourceTarget&&source?.sourceUrl&&createPortal(<SourceSync source={source} onSource={setSource}/>,sourceTarget)}{labTarget&&analysis?.result&&createPortal(<details className="aeonLab"><summary><div><span>{t('EXPERIMENTAL','EXPÉRIMENTAL')}</span><b>{t('Aeon Lab','Laboratoire Aeon')}</b><small>{t('Advanced evidence, counterfactuals and card-by-card semantic review. Nothing in this section replaces the median, P20, P80 or peak.','Preuves avancées, contrefactuels et vérification sémantique carte par carte. Rien ici ne remplace la médiane, P20, P80 ou le pic.')}</small></div><i>+</i></summary><div className="aeonLabBody"><IntelligenceGlossary intel={localIntelligence} lang={lang}/><CardSemanticAudit cards={localCards} lang={lang}/><ComboTiming comboAccessibility={localIntelligence?.comboAccessibility} lang={lang}/><SuppressionStress spof={localIntelligence?.spof} lang={lang}/><Rule0Tools lang={lang} analysisId={analysisId} result={analysis.result} cards={localCards} decklist={analysis.decklist} commanderNames={analysis.commanderNames}/></div></details>,labTarget)}</>
}
