import { useEffect,useMemo,useState } from 'react'
import { AEON_LABEL,ENGINE_VERSION,SEMANTIC_VERSION } from './version.js'
import { COLOR_ORDER,filterPublicDecks,publicDeckColorKey,publicDeckSpread,publicDeckStats,publicDeckStatus,sortPublicDecks } from './publicDecksModel.js'

const t=(lang,en,fr)=>lang==='fr'?fr:en
const SITE_URL='https://aeon-scorer.vercel.app'
const COLORS={W:'W',U:'U',B:'B',R:'R',G:'G',C:'C'}
const METRICS=[['median','Median','Médiane'],['p20','P20','P20'],['p80','P80','P80'],['peak','Peak','Pic']]
const DIM_LABELS={speed:['Speed','Vitesse'],consistency:['Consistency','Consistance'],explosiveness:['Explosiveness','Explosivité'],synergy:['Synergy','Synergie'],interaction:['Interaction','Interaction'],resilience:['Recovery','Reprise']}
const PACKAGE_LABELS={
  'early-commander':['Commander acceleration','Accélération commandant'],'blink-etb':['Blink / ETB','Blink / ETB'],constellation:['Enchantments / Constellation','Enchantements / Constellation'],tokens:['Tokens / conversion','Tokens / conversion'],sacrifice:['Sacrifice / death','Sacrifice / mort'],graveyard:['Graveyard / recursion','Cimetière / récursion'],lands:['Lands / Landfall','Lands / Landfall'],counters:['Counters','Marqueurs'],spells:['Spellslinger','Spellslinger'],exile:['Exile casting','Jeu depuis l’exil'],artifacts:['Artifacts','Artefacts']
}

function currentLang(){return localStorage.getItem('aeon-lang')==='fr'?'fr':'en'}
function setLanguage(lang){localStorage.setItem('aeon-lang',lang);document.documentElement.lang=lang;window.dispatchEvent(new StorageEvent('storage',{key:'aeon-lang',newValue:lang}))}
function isModifiedClick(e){return e.button!==0||e.metaKey||e.ctrlKey||e.shiftKey||e.altKey}
function go(path){window.history.pushState({},'',path);window.dispatchEvent(new PopStateEvent('popstate'));window.scrollTo({top:0,behavior:'smooth'})}
function Nav({lang,onLang}){const L=(en,fr)=>t(lang,en,fr);return <div className="navFrame"><nav className="siteNav publicSiteNav" aria-label={L('Main navigation','Navigation principale')}>
  <a className="brand" href="/" onClick={e=>{if(isModifiedClick(e))return;e.preventDefault();location.href='/'}}><span className="brandMark"><i>A</i></span><span className="brandText"><b>Aeon Scorer</b><small>{L('Commander power analyzer','Analyseur de puissance Commander')}</small></span></a>
  <div className="navLinks"><a href="/">{L('Analyze','Analyser')}</a><a href="/decklists-publiques" className="active">{L('Public decks','Decklists publiques')}</a><a href="/pourquoi">{L('Why','Pourquoi')}</a><a href="/methodologie">{L('Methodology','Méthodologie')}</a><a href="/a-propos">{L('About','À propos')}</a></div>
  <div className="navActions"><div className="languageSwitch"><button className={lang==='en'?'active':''} onClick={()=>onLang('en')}>EN</button><button className={lang==='fr'?'active':''} onClick={()=>onLang('fr')}>FR</button></div><a className="navExternal" href="https://github.com/megazz31/aeon-scorer" target="_blank" rel="noreferrer">GitHub <span>↗</span></a></div>
</nav></div>}
function ColorPips({colors=[]}){const cs=colors.filter(x=>COLOR_ORDER.includes(x));const shown=cs.length?cs:['C'];return <span className="colorPips" aria-label={shown.join('')}>{shown.map(c=><i className={`manaPip mana-${c}`} key={c}>{COLORS[c]}</i>)}</span>}
function Metric({label,value,accent=false}){return <div className={`publicMetric${accent?' accent':''}`}><span>{label}</span><strong>{value??'—'}</strong></div>}
function Bar({label,value}){const n=Math.max(0,Math.min(100,Number(value)||0));return <div className="publicBar"><div><span>{label}</span><b>{value??'—'}</b></div><i><em style={{width:`${n}%`}}/></div>}
function StatusBadge({deck,lang}){const s=publicDeckStatus(deck,ENGINE_VERSION,SEMANTIC_VERSION),label={current:t(lang,'Current Aeon','Aeon à jour'),outdated:t(lang,'Re-audit needed','Réanalyse requise'),pending:t(lang,'Awaiting analysis','Analyse en attente'),unsupported:t(lang,'Not yet supported','Pas encore géré')}[s];return <span className={`publicStatus ${s}`}>{label}</span>}
function SourceBadge({deck,lang}){return <span className="sourceBadge">{t(lang,'Official decklist source','Source decklist officielle')} · {deck.sourceName||'MTGJSON'}</span>}
function formatDate(date,lang){if(!date)return '—';try{return new Intl.DateTimeFormat(lang==='fr'?'fr-FR':'en-US',{year:'numeric',month:'short',day:'numeric'}).format(new Date(`${date}T00:00:00Z`))}catch{return date}}
function reason(reason,lang){const map={multiple_commanders_not_supported:t(lang,'Two-commanders / Partner / Background is not modeled yet.','Deux commandants / Partner / Background n’est pas encore modélisé.'),commander_missing:t(lang,'Commander metadata is missing.','Métadonnée commandant manquante.'),commander_unresolved_by_scryfall:t(lang,'Commander could not be resolved independently.','Le commandant n’a pas pu être résolu indépendamment.')};return map[reason]||String(reason||t(lang,'Not currently analyzable.','Non analysable actuellement.')).replace(/^scryfall_unresolved_(\d+)_cards$/,(_,n)=>t(lang,`${n} card(s) could not be resolved independently.`,`${n} carte(s) n’ont pas pu être résolues indépendamment.`))}

function CatalogCard({deck,lang,onOpen}){const L=(en,fr)=>t(lang,en,fr),a=deck.analysis;return <article className={`publicDeckCard${deck.supported?'':' unsupported'}`} tabIndex="0" role="link" onClick={onOpen} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onOpen()}}}>
  <div className="publicDeckImage">{deck.commanderImageUrl?<img src={deck.commanderImageUrl} alt={deck.commanderName} loading="lazy"/>:<div className="imageFallback">A</div>}<div className="cardImageShade"/><div className="publicDeckImageTop"><StatusBadge deck={deck} lang={lang}/><ColorPips colors={deck.colorIdentity}/></div><div className="publicDeckIdentity"><small>{deck.setCode||L('Commander precon','Précon Commander')} · {String(deck.releaseDate||'').slice(0,4)||'—'}</small><h2>{deck.name}</h2><p>{deck.commanderName}</p></div></div>
  <div className="publicDeckCardBody">{a?<><div className="publicHeadline"><div><span>{L('Median','Médiane')}</span><strong>{a.median}</strong></div><div><span>P20–P80</span><b>{a.p20}–{a.p80}</b></div><div><span>{L('Peak','Pic')}</span><b>{a.peak}</b></div></div><div className="miniRange"><i style={{left:`${Math.max(0,Math.min(100,a.p20))}%`,width:`${Math.max(1,Math.min(100,a.p80)-Math.max(0,a.p20))}%`}}/><em style={{left:`${Math.max(0,Math.min(100,a.median))}%`}}/><b style={{left:`${Math.max(0,Math.min(100,a.peak))}%`}}/></div><small className="cardVersion">Aeon v{a.engineVersion} · {Number(a.iterations||0).toLocaleString(lang==='fr'?'fr-FR':'en-US')} {L('sequences','séquences')}</small></>:<div className="publicPending"><b>{deck.supported?L('Waiting for its first Aeon analysis','En attente de sa première analyse Aeon'):L('Catalogued, not scored','Catalogué, non scoré')}</b><span>{deck.supported?L('The official decklist is stored and will be analyzed by the current engine.','La decklist officielle est stockée et sera analysée par le moteur courant.'):reason(deck.unsupportedReason,lang)}</span></div>}<button className="openPublicDeck">{L('Open analysis','Ouvrir l’analyse')} <i>→</i></button></div>
</article>}

const EMPTY_FILTERS={search:'',colors:[],colorMode:'contains',yearMin:'',yearMax:'',status:'all',medianMin:'',medianMax:'',p20Min:'',p20Max:'',p80Min:'',p80Max:'',peakMin:'',peakMax:'',sort:'release',direction:'desc'}
function Filters({filters,setFilters,years,lang,count,total}){const L=(en,fr)=>t(lang,en,fr),set=(key,value)=>setFilters(x=>({...x,[key]:value})),toggleColor=c=>setFilters(x=>({...x,colors:x.colors.includes(c)?x.colors.filter(v=>v!==c):[...x.colors,c]}));return <section className="publicFilters">
  <div className="filterPrimary"><label className="searchField"><span>{L('Search','Recherche')}</span><input value={filters.search} onChange={e=>set('search',e.target.value)} placeholder={L('Deck, commander, product, set…','Deck, commandant, produit, set…')}/></label><label><span>{L('Sort by','Trier par')}</span><select value={filters.sort} onChange={e=>set('sort',e.target.value)}><option value="release">{L('Release date','Date de sortie')}</option><option value="name">{L('Deck name','Nom du deck')}</option><option value="commander">Commander</option><option value="median">{L('Median','Médiane')}</option><option value="p20">P20</option><option value="p80">P80</option><option value="peak">{L('Peak','Pic')}</option><option value="spread">{L('P20–P80 spread','Amplitude P20–P80')}</option><option value="coverage">{L('Coverage','Couverture')}</option></select></label><button className="directionButton" onClick={()=>set('direction',filters.direction==='desc'?'asc':'desc')} title={L('Reverse sort','Inverser le tri')}>{filters.direction==='desc'?'↓':'↑'}</button></div>
  <div className="filterRow"><div className="filterGroup"><span>{L('Colors','Couleurs')}</span><div className="colorFilters">{[...COLOR_ORDER,'C'].map(c=><button key={c} className={filters.colors.includes(c)?'active':''} onClick={()=>toggleColor(c)}><i className={`manaPip mana-${c}`}>{c}</i></button>)}</div><div className="segmented"><button className={filters.colorMode==='contains'?'active':''} onClick={()=>set('colorMode','contains')}>{L('Contains','Contient')}</button><button className={filters.colorMode==='exact'?'active':''} onClick={()=>set('colorMode','exact')}>{L('Exact identity','Identité exacte')}</button></div></div><label><span>{L('From year','Depuis')}</span><select value={filters.yearMin} onChange={e=>set('yearMin',e.target.value)}><option value="">{L('Any','Toutes')}</option>{years.map(y=><option key={y} value={y}>{y}</option>)}</select></label><label><span>{L('To year','Jusqu’à')}</span><select value={filters.yearMax} onChange={e=>set('yearMax',e.target.value)}><option value="">{L('Any','Toutes')}</option>{years.map(y=><option key={y} value={y}>{y}</option>)}</select></label><label><span>{L('Analysis state','État analyse')}</span><select value={filters.status} onChange={e=>set('status',e.target.value)}><option value="all">{L('All','Tous')}</option><option value="current">{L('Current Aeon','Aeon à jour')}</option><option value="outdated">{L('Re-audit needed','Réanalyse requise')}</option><option value="pending">{L('Awaiting analysis','En attente')}</option><option value="unsupported">{L('Not supported yet','Pas encore géré')}</option></select></label></div>
  <details className="metricFilters"><summary>{L('Power filters','Filtres de puissance')} <small>{L('median · P20 · P80 · peak','médiane · P20 · P80 · pic')}</small></summary><div className="metricFilterGrid">{METRICS.map(([key,en,fr])=><div className="metricFilter" key={key}><b>{t(lang,en,fr)}</b><label><span>Min</span><input type="number" min="0" max="100" value={filters[`${key}Min`]} onChange={e=>set(`${key}Min`,e.target.value)} placeholder="0"/></label><label><span>Max</span><input type="number" min="0" max="100" value={filters[`${key}Max`]} onChange={e=>set(`${key}Max`,e.target.value)} placeholder="100"/></label></div>)}</div></details>
  <div className="filterFoot"><span><b>{count}</b> / {total} {L('public decks','decklists publiques')}</span><button onClick={()=>setFilters({...EMPTY_FILTERS})}>{L('Reset filters','Réinitialiser')}</button></div>
</section>}

function Catalog({catalog,lang,onOpen}){const L=(en,fr)=>t(lang,en,fr),[filters,setFilters]=useState({...EMPTY_FILTERS}),years=useMemo(()=>[...new Set(catalog.map(d=>Number(String(d.releaseDate||'').slice(0,4))).filter(Number.isFinite))].sort((a,b)=>b-a),[catalog]),filtered=useMemo(()=>sortPublicDecks(filterPublicDecks(catalog,filters,{engineVersion:ENGINE_VERSION,semanticVersion:SEMANTIC_VERSION}),filters.sort,filters.direction),[catalog,filters]),stats=useMemo(()=>publicDeckStats(catalog,{engineVersion:ENGINE_VERSION,semanticVersion:SEMANTIC_VERSION}),[catalog]);return <>
  <header className="publicHero"><div><span className="sectionEyebrow">{L('PUBLIC DECKLISTS','DECKLISTS PUBLIQUES')}</span><h1>{L('Every precon, measured the same way.','Tous les précons, mesurés de la même façon.')}</h1><p>{L('Official Commander precon decklists become a permanent Aeon reference library. The lists stay fixed; their Aeon analysis is versioned and re-run as the engine improves.','Les decklists officielles des précons Commander deviennent une bibliothèque de référence permanente pour Aeon. Les listes restent fixes ; leur analyse Aeon est versionnée et relancée à mesure que le moteur progresse.')}</p></div><div className="publicHeroStats"><div><strong>{stats.total}</strong><span>{L('canonical decks','decklists canoniques')}</span></div><div><strong>{stats.current}</strong><span>{L(`current on ${AEON_LABEL}`,`à jour sur ${AEON_LABEL}`)}</span></div><div><strong>{stats.outdated+stats.pending}</strong><span>{L('to analyze / re-audit','à analyser / réauditer')}</span></div></div></header>
  <div className="publicTruthNote"><b>{L('A benchmark, not a label.','Un benchmark, pas une vérité imposée.')}</b><span>{L('Precon results expand semantic QA and regression coverage. Aeon never assumes that a precon “must” have a specific score.','Les résultats des précons enrichissent la QA sémantique et la couverture de régression. Aeon ne considère jamais qu’un précon « doit » avoir un score précis.')}</span></div>
  <Filters filters={filters} setFilters={setFilters} years={years} lang={lang} count={filtered.length} total={catalog.length}/>
  {filtered.length?<div className="publicDeckGrid">{filtered.map(deck=><CatalogCard key={deck.slug} deck={deck} lang={lang} onOpen={()=>onOpen(deck.slug)}/>)}</div>:<div className="publicEmpty"><b>{L('No precon matches these filters.','Aucun précon ne correspond à ces filtres.')}</b><span>{L('Try widening a power range or resetting colors.','Élargis une plage de puissance ou réinitialise les couleurs.')}</span></div>}
</>}

function Detail({detail,lang,onBack}){const L=(en,fr)=>t(lang,en,fr),[tab,setTab]=useState('summary'),a=detail.analysis,r=detail.result,[copied,setCopied]=useState(false);const copy=async()=>{await navigator.clipboard.writeText(detail.decklist||'');setCopied(true);setTimeout(()=>setCopied(false),1400)};return <>
  <button className="backPublic" onClick={onBack}>← {L('All public decks','Toutes les decklists publiques')}</button>
  <header className="publicDetailHero"><div className="detailArt">{detail.commanderImageUrl?<img src={detail.commanderImageUrl} alt={detail.commanderName}/>:<div className="imageFallback">A</div>}</div><div className="detailIntro"><div className="detailBadges"><StatusBadge deck={detail} lang={lang}/><SourceBadge deck={detail} lang={lang}/></div><span className="sectionEyebrow">{detail.setCode||L('COMMANDER PRECON','PRÉCON COMMANDER')} · {formatDate(detail.releaseDate,lang)}</span><h1>{detail.name}</h1><p>{detail.commanderName}</p><ColorPips colors={detail.colorIdentity}/>{a?<div className="detailVersion">Aeon v{a.engineVersion} · semantic {a.semanticVersion} · {Number(a.iterations||0).toLocaleString(lang==='fr'?'fr-FR':'en-US')} {L('sequences','séquences')} · Oracle {a.scryfallOracleDate}</div>:<div className="detailVersion">{reason(detail.unsupportedReason,lang)}</div>}</div>{a&&<div className="detailScore"><span>{L('Median power','Puissance médiane')}</span><strong>{a.median}</strong><small>/100</small></div>}</header>
  {a&&<section className="detailMetricStrip"><Metric label="P20" value={a.p20}/><Metric label={L('Median','Médiane')} value={a.median}/><Metric label="P80" value={a.p80}/><Metric label={L('Peak','Pic')} value={a.peak} accent/><Metric label={L('Coverage','Couverture')} value={`${a.coverage}%`}/><Metric label={L('Spread','Amplitude')} value={publicDeckSpread(detail)}/></section>}
  <nav className="publicTabs">{[['summary',L('Summary','Résumé')],['diagnostic',L('Detailed diagnostic','Diagnostic détaillé')],['decklist','Decklist']].map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</nav>
  {!r&&<section className="panel publicNoAnalysis"><h2>{detail.supported?L('Analysis pending','Analyse en attente'):L('Not modeled yet','Pas encore modélisé')}</h2><p>{detail.supported?L('This official list is catalogued but has no analysis for the current public snapshot yet.','Cette liste officielle est cataloguée mais n’a pas encore d’analyse dans le snapshot public courant.'):reason(detail.unsupportedReason,lang)}</p></section>}
  {r&&tab==='summary'&&<div className="publicDetailStack"><section className="panel"><div className="panelHeading"><div><span className="sectionEyebrow">{L('POWER DISTRIBUTION','DISTRIBUTION DE PUISSANCE')}</span><h2>{a.median} [{a.p20}–{a.p80}] · {L('peak','pic')} {a.peak}</h2></div></div><div className="detailScale"><i style={{left:`${a.p20}%`,width:`${Math.max(1,a.p80-a.p20)}%`}}/><em style={{left:`${a.median}%`}}/><b style={{left:`${a.peak}%`}}/></div><p className="note">{L('Compare median first, then the usual P20–P80 range and finally peak. These values are Aeon model outputs, not a published Wizards power rating.','Compare d’abord la médiane, puis la plage habituelle P20–P80 et enfin le pic. Ces valeurs sont des sorties du modèle Aeon, pas une note de puissance publiée par Wizards.')}</p></section><section className="publicTwoCols"><div className="panel"><div className="panelHeading compact"><div><span className="sectionEyebrow">{L('DIMENSIONS','DIMENSIONS')}</span><h2>{L('Why this score?','Pourquoi ce score ?')}</h2></div></div>{Object.entries(r.dimensions||{}).map(([k,v])=><Bar key={k} label={t(lang,...(DIM_LABELS[k]||[k,k]))} value={v}/>)}</div><div className="panel"><div className="panelHeading compact"><div><span className="sectionEyebrow">{L('STRUCTURE','STRUCTURE')}</span><h2>{L('Detected deck','Deck détecté')}</h2></div></div><div className="detailMiniGrid"><Metric label={L('Lands','Terrains')} value={r.roles?.lands}/><Metric label={L('Avg. mana value','MV moyen')} value={Number(r.roles?.avgCmc||0).toFixed(2)}/><Metric label="Fast mana" value={r.roles?.fastMana}/><Metric label="Tutors" value={r.roles?.tutors}/></div></div></section>{r.combos?.length>0&&<section className="panel"><div className="panelHeading compact"><div><span className="sectionEyebrow">COMBOS</span><h2>{L('Known combos detected','Combos connues détectées')}</h2></div></div>{r.combos.map(c=><div className="publicCombo" key={c.name}><b>{c.name}</b><span>{(c.cards||[]).join(' + ')}</span></div>)}</section>}</div>}
  {r&&tab==='diagnostic'&&<div className="publicDetailStack"><section className="panel"><div className="panelHeading"><div><span className="sectionEyebrow">{L('ACCESS','ACCÈS')}</span><h2>{L('Turn-by-turn curve','Courbe par tour')}</h2></div></div><div className="publicTurnTable"><div className="publicTurnHead"><span>{L('Turn','Tour')}</span><span>Commander</span><span>{L('Package','Package')}</span><span>{L('Interaction','Interaction')}</span><span>{L('Resource','Ressource')}</span><span>Burst</span></div>{(r.simulation?.turnProfile||[]).map(x=><div className="publicTurnLine" key={x.turn}><b>T{x.turn}</b><span>{x.commander}%</span><span>{x.engine}%</span><span>{x.interaction}%</span><span>{x.resource}%</span><span>{x.burst}%</span></div>)}</div></section><section className="publicTwoCols"><div className="panel"><div className="panelHeading compact"><div><span className="sectionEyebrow">{L('SYNERGIES','SYNERGIES')}</span><h2>{L('Detected packages','Packages détectés')}</h2></div></div>{r.packages?.length?(r.packages||[]).map(p=><article className="publicPackage" key={p.id}><div><b>{t(lang,...(PACKAGE_LABELS[p.id]||[p.name||p.id,p.name||p.id]))}</b><span>{L('cohesion','cohésion')} {p.cohesion??p.strength}/100</span></div><small><b>{L('Producers','Producteurs')}:</b> {(p.producers||[]).join(' · ')||'—'}</small><small><b>Payoffs:</b> {(p.payoffs||[]).join(' · ')||'—'}</small></article>):<p className="muted">{L('No supported package detected.','Aucun package suffisamment étayé détecté.')}</p>}</div><div className="panel"><div className="panelHeading compact"><div><span className="sectionEyebrow">{L('MAIN DRIVERS','PRINCIPAUX DRIVERS')}</span><h2>{L('Structural impact','Impact structurel')}</h2></div></div>{(r.drivers||[]).map(d=><div className="publicDriver" key={d.name}><span><b>{d.name}</b><small>{(d.tags||[]).slice(0,4).join(' · ')}</small></span><strong>{d.impact}</strong></div>)}</div></section>{(r.warnings||[]).length>0&&<section className="panel publicWarnings"><div className="sectionEyebrow">{L('LIMITS / WARNINGS','LIMITES / ALERTES')}</div>{r.warnings.map((w,i)=><p key={i}>• {w}</p>)}</section>}</div>}
  {tab==='decklist'&&<section className="panel decklistPanel"><div className="decklistHead"><div><span className="sectionEyebrow">{L('OFFICIAL LIST','LISTE OFFICIELLE')}</span><h2>{detail.cardCount} {L('cards in the imported mainboard','cartes dans le mainboard importé')}</h2></div><button onClick={copy}>{copied?L('Copied','Copié'):L('Copy decklist','Copier la decklist')}</button></div><pre>{detail.decklist||L('Decklist unavailable.','Decklist indisponible.')}</pre><div className="deckSourceFoot"><span>{L('Source','Source')}: {detail.sourceName||'MTGJSON'} · {L('revision','révision')} {detail.sourceRevision||'—'}</span>{detail.sourceUrl&&<a href={detail.sourceUrl} target="_blank" rel="noreferrer">{L('Open source data','Ouvrir les données source')} ↗</a>}</div></section>}
</>}

export default function PublicDecksPage(){
  const[lang,setLangState]=useState(()=>currentLang()),[catalog,setCatalog]=useState([]),[meta,setMeta]=useState(null),[detail,setDetail]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[path,setPath]=useState(()=>window.location.pathname)
  const slug=path.startsWith('/decklists-publiques/')?decodeURIComponent(path.slice('/decklists-publiques/'.length).replace(/\/+$/,'')):null,L=(en,fr)=>t(lang,en,fr)
  useEffect(()=>{const pop=()=>setPath(window.location.pathname);window.addEventListener('popstate',pop);return()=>window.removeEventListener('popstate',pop)},[])
  useEffect(()=>{let alive=true;setLoading(true);setError('');fetch('/precons/catalog.json').then(r=>{if(!r.ok)throw new Error(`Catalog HTTP ${r.status}`);return r.json()}).then(x=>{if(!alive)return;setCatalog(x.data||[]);setMeta(x.meta||null)}).catch(e=>alive&&setError(e.message||String(e))).finally(()=>alive&&setLoading(false));return()=>{alive=false}},[])
  useEffect(()=>{let alive=true;if(!slug){setDetail(null);return}setLoading(true);setError('');fetch(`/precons/${encodeURIComponent(slug)}.json`).then(r=>{if(!r.ok)throw new Error(`Deck HTTP ${r.status}`);return r.json()}).then(x=>alive&&setDetail(x)).catch(e=>alive&&setError(e.message||String(e))).finally(()=>alive&&setLoading(false));return()=>{alive=false}},[slug])
  useEffect(()=>{document.documentElement.lang=lang;document.title=slug?`${detail?.name||L('Public deck','Deck public')} — Aeon Scorer`:L('Public Commander precons — Aeon Scorer','Précons Commander publics — Aeon Scorer');let c=document.querySelector('link[rel="canonical"]');if(!c){c=document.createElement('link');c.rel='canonical';document.head.appendChild(c)}c.href=`${SITE_URL}${path}`},[lang,path,slug,detail?.name])
  const changeLang=next=>{setLanguage(next);setLangState(next)}
  return <div className="appRoot publicDecksRoot"><Nav lang={lang} onLang={changeLang}/><main className="publicDecksMain">{loading&&<div className="publicLoading"><i/><span>{L('Loading public deck library…','Chargement de la bibliothèque publique…')}</span></div>}{error&&!loading&&<div className="publicError"><b>{L('Public library unavailable','Bibliothèque publique indisponible')}</b><span>{error}</span><a href="/">{L('Back to analyzer','Retour à l’analyseur')}</a></div>}{!loading&&!error&&(slug&&detail?<Detail detail={detail} lang={lang} onBack={()=>go('/decklists-publiques')}/>:<Catalog catalog={catalog} meta={meta} lang={lang} onOpen={s=>go(`/decklists-publiques/${encodeURIComponent(s)}`)}/>)}</main><footer><div className="footerInner"><div><a href="/">Aeon Scorer</a><span>{L('Versioned public Commander benchmark library','Bibliothèque publique de benchmarks Commander versionnés')}</span></div><small>{AEON_LABEL} · {ENGINE_VERSION} · {L('precon scores are evidence, never truth labels','les scores précons sont des indices, jamais des labels vérité')}</small></div></footer></div>
}
