import { useEffect,useMemo,useState } from 'react'
import { createAnalysisShare,submitAnalysisFeedback } from './supabaseClient.js'
import { deckDiff,localBracketSignals,resultDelta } from './productData.js'
import { parseDecklist,fetchCards,fetchCard } from './scryfall.js'
import { analyzePower } from './engine/powerModel.js'
import { buildDeckIntelligence,buildShareableIntelligence } from './engine/roadmapEngine.js'

const t=(lang,en,fr)=>lang==='fr'?fr:en
const pretty=s=>String(s||'').replace(/([a-z])([A-Z])/g,'$1 $2').replace(/-/g,' ')
export default function Rule0Tools({lang='en',analysisId,result,cards=[],decklist='',commanderNames=[]}){
  const[insights,setInsights]=useState(null),[insightError,setInsightError]=useState(''),[shareUrl,setShareUrl]=useState(''),[shareBusy,setShareBusy]=useState(false)
  const[feedbackType,setFeedbackType]=useState('card_semantics'),[feedback,setFeedback]=useState(''),[feedbackState,setFeedbackState]=useState('')
  const[draft,setDraft]=useState(decklist),[preview,setPreview]=useState(null),[whatBusy,setWhatBusy]=useState(false),[whatError,setWhatError]=useState('')
  const L=(en,fr)=>t(lang,en,fr)
  useEffect(()=>setDraft(decklist),[decklist])
  useEffect(()=>{let dead=false;if(!decklist||!commanderNames.length)return;setInsightError('');fetch('/api/commander-insights',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({decklist,commanders:commanderNames})}).then(async r=>{const x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(x.error||'Insights unavailable');if(!dead)setInsights(x)}).catch(e=>{if(!dead)setInsightError(e.message||String(e))});return()=>{dead=true}},[decklist,commanderNames.join('|')])
  const signals=useMemo(()=>localBracketSignals(cards,result,insights),[cards,result,insights])
  const deckIntelligence=useMemo(()=>result?buildDeckIntelligence(result,cards):null,[result,cards])
  const shareIntelligence=useMemo(()=>result?buildShareableIntelligence(result,cards):{},[result,cards])
  async function share(){if(!analysisId)return;setShareBusy(true);try{const code=await createAnalysisShare(analysisId,{gameChangers:signals.gameChangers,bracketSignals:{...signals,spellbookBracket:insights?.bracketTag||null,twoCardCombos:insights?.twoCardCombos||signals.twoCardCombos},comboSummary:insights?.included||result?.combos||[],productIntelligence:shareIntelligence});const url=`${location.origin}/a/${code}`;setShareUrl(url);await navigator.clipboard?.writeText(url)}catch(e){setShareUrl(`ERROR: ${e.message||e}`)}finally{setShareBusy(false)}}
  async function report(){if(!analysisId)return;setFeedbackState('');try{await submitAnalysisFeedback(analysisId,feedbackType,feedback);setFeedback('');setFeedbackState(L('Sent to semantic audit queue.','Envoyé dans la file d’audit sémantique.'))}catch(e){setFeedbackState(e.message||String(e))}}
  async function runWhatIf(){setWhatBusy(true);setWhatError('');setPreview(null);try{const parsed=parseDecklist(draft),total=parsed.reduce((s,x)=>s+x.qty,0),expected=100-Math.max(1,commanderNames.length);if(total!==expected)throw new Error(L(`Variant has ${total} cards; expected ${expected} main-deck cards for ${commanderNames.length||1} commander(s).`,`La variante contient ${total} cartes ; ${expected} cartes de deck sont attendues avec ${commanderNames.length||1} commandant(s).`));const fetched=await fetchCards(parsed);if(fetched.length!==total)throw new Error(L('Some variant cards could not be resolved.','Certaines cartes de la variante n’ont pas été résolues.'));const commanders=(await Promise.all(commanderNames.map(fetchCard))).filter(Boolean);if(commanders.length!==commanderNames.length)throw new Error(L('One or more commanders could not be resolved.','Un ou plusieurs commandants sont introuvables.'));setPreview(analyzePower(fetched,commanders.length===1?commanders[0]:commanders,null,1500,{emitProduct:false,record:false}))}catch(e){setWhatError(e.message||String(e))}finally{setWhatBusy(false)}}
  const diff=useMemo(()=>deckDiff(decklist,draft),[decklist,draft]),delta=useMemo(()=>resultDelta(result,preview),[result,preview])
  const sourceStatus=signals.sourceStatus||{},experience=Object.entries(result?.experience?.dimensions||{}),friction=Object.entries(result?.friction?.signals||{}).filter(([,v])=>(v?.score||0)>0),spof=deckIntelligence?.spof,vulnerabilities=deckIntelligence?.vulnerability?.highest||[],comboAccess=deckIntelligence?.comboAccessibility?.highest
  return <section className="rule0Tools"><div className="rule0ToolsHead"><div><span className="sectionEyebrow">RULE 0</span><h3>{L('Share, compare and challenge the result','Partager, comparer et challenger le résultat')}</h3></div>{insights?.source&&<small>Commander Spellbook</small>}</div>
    <div className="insightGrid"><div className="insightCard"><b>{L('Commander Brackets signals','Signaux Commander Brackets')}</b><small>{signals.gameChangerCount} Game Changer(s){insights?.bracketTag?` · Spellbook ${insights.bracketTag}`:''}{insights?.extraTurnCards?.length?` · ${insights.extraTurnCards.length} extra-turn card(s)`:''}</small>{signals.gameChangers.length>0&&<p>{signals.gameChangers.join(' · ')}</p>}<small>{sourceStatus.status==='review-needed'?L(`Game Changers snapshot needs review · last checked ${sourceStatus.reviewedAt}`,`Le snapshot Game Changers doit être revu · dernier contrôle ${sourceStatus.reviewedAt}`):L(`Wizards list reviewed ${sourceStatus.reviewedAt}`,`Liste Wizards contrôlée le ${sourceStatus.reviewedAt}`)}</small></div><div className="insightCard"><b>Commander Spellbook</b><small>{insights?L(`${insights.included.length} complete combo(s) · ${insights.almostIncluded.length} one-card-away line(s)`,`${insights.included.length} combo(s) complète(s) · ${insights.almostIncluded.length} ligne(s) à une carte`):insightError||L('Loading combo evidence…','Chargement des combos…')}</small>{insights?.included?.slice(0,3).map(c=><p key={c.id||c.cards.join('|')}>{c.cards.join(' + ')}</p>)}</div></div>
    <details className="whatIf intelligencePanel" open><summary>{L('Aeon Experience Intelligence · experimental','Aeon Experience Intelligence · expérimental')}</summary><p className="productNote">{L('These signals describe game experience, dependency and vulnerability separately from the 0–100 power score.','Ces signaux décrivent expérience, dépendance et vulnérabilité séparément du score de puissance 0–100.')}</p><div className="insightGrid"><div className="insightCard"><b>{L('Experience fingerprint','Empreinte d’expérience')}</b>{experience.map(([k,v])=><p key={k}>{pretty(k)} · <strong>{v.score}</strong> · {v.level}</p>)}</div><div className="insightCard"><b>{L('Table characteristics','Caractéristiques de table')}</b>{friction.length?friction.slice(0,6).map(([k,v])=><p key={k}>{pretty(k)} · <strong>{v.score}</strong> · {v.level}</p>):<p>{L('No material friction signal detected.','Aucun signal de friction significatif détecté.')}</p>}</div><div className="insightCard"><b>SPOF</b>{spof?.highest?<><p>{pretty(spof.highest.kind)} · <strong>{spof.highest.score}</strong> · {spof.highest.level}</p><small>{spof.highest.method}</small></>:<p>—</p>}{comboAccess&&<p>{L('Combo access proxy','Proxy accès combo')} · <strong>{comboAccess.score}</strong> · {comboAccess.level}</p>}</div><div className="insightCard"><b>{L('Top vulnerabilities','Vulnérabilités principales')}</b>{vulnerabilities.length?vulnerabilities.map(v=><p key={v.kind}>{pretty(v.kind)} · <strong>{v.score}</strong> · {v.level}</p>):<p>—</p>}</div></div><p className="productNote">{L('Product calibration is experimental. No exact “good game probability” is claimed yet.','La calibration produit est expérimentale. Aucune « probabilité exacte de bonne partie » n’est encore revendiquée.')}</p></details>
    <div className="rule0ToolButtons"><button onClick={share} disabled={!analysisId||shareBusy}>{shareBusy?L('Creating link…','Création du lien…'):L('Share Rule 0 card','Partager la carte Rule 0')}</button><a href="/pod">Pod Match</a>{shareUrl&&<span>{shareUrl.startsWith('ERROR:')?shareUrl:<a href={shareUrl}>{L('Open shared card','Ouvrir le partage')}</a>}</span>}</div>
    <div className="feedbackBox"><select value={feedbackType} onChange={e=>setFeedbackType(e.target.value)}><option value="card_semantics">{L('Card misread','Carte mal comprise')}</option><option value="package">{L('Wrong package','Package incorrect')}</option><option value="combo">{L('Combo issue','Problème combo')}</option><option value="mana">{L('Mana issue','Problème mana')}</option><option value="score_surprise">{L('Surprising score','Score surprenant')}</option><option value="other">{L('Other','Autre')}</option></select><input value={feedback} onChange={e=>setFeedback(e.target.value)} maxLength={1500} placeholder={L('Optional detail for the auditor…','Détail facultatif pour l’auditeur…')}/><button onClick={report} disabled={!analysisId}>{L('Report','Signaler')}</button></div>{feedbackState&&<p className="productNote">{feedbackState}</p>}
    <details className="whatIf"><summary>{L('What if? Test a modified list','What if ? Tester une liste modifiée')}</summary><p className="productNote">{L('Edit the main-deck list below and run a fast 1,500-sequence preview. Command-zone cards stay separate and the preview is never persisted.','Modifie la liste du deck ci-dessous et lance un aperçu rapide à 1 500 séquences. Les cartes de zone de commandement restent séparées et l’aperçu n’est jamais enregistré.')}</p><textarea value={draft} onChange={e=>setDraft(e.target.value)}/><div className="deckDiff"><div><b>+ {L('Added','Ajouté')}</b><ul>{diff.added.slice(0,12).map(x=><li key={x.name}>{x.qty} {x.name}</li>)}</ul></div><div><b>− {L('Removed','Retiré')}</b><ul>{diff.removed.slice(0,12).map(x=><li key={x.name}>{x.qty} {x.name}</li>)}</ul></div></div><button className="productPrimary" onClick={runWhatIf} disabled={whatBusy||!diff.changes}>{whatBusy?L('Analyzing…','Analyse…'):L('Analyze variant','Analyser la variante')}</button>{whatError&&<div className="productError">{whatError}</div>}{delta&&<div className="whatIfDelta"><span>{L('Median','Médiane')} {delta.median>=0?'+':''}{delta.median}</span><span>P20 {delta.floor>=0?'+':''}{delta.floor}</span><span>P80 {delta.ceiling>=0?'+':''}{delta.ceiling}</span><span>{L('Peak','Pic')} {delta.peak>=0?'+':''}{delta.peak}</span></div>}</details>
  </section>}
