export const SITE_META={
  en:{
    '/':{title:'Aeon Scorer — MTG Commander Deck Power Level Analyzer',description:'Estimate the power of a Magic: The Gathering Commander deck with Monte Carlo simulations, card synergies, mana access and a readable power distribution.'},
    '/pourquoi':{title:'Why Aeon Scorer? — Commander deck power beyond brackets',description:'Why Commander Brackets and subjective ratings are not enough to compare deck output, and how Aeon Scorer models a power distribution.'},
    '/methodologie':{title:'Methodology — Aeon Scorer',description:'How Aeon Scorer analyzes Commander decks through card roles, synergy packages, mana access, Monte Carlo simulation, calibration and known limitations.'},
    '/a-propos':{title:'About — Aeon Scorer',description:'The origin of Aeon Scorer, an independent open-source project for comparing Magic: The Gathering Commander deck power.'}
  },
  fr:{
    '/':{title:'Aeon Scorer — Analyseur de puissance de deck MTG Commander',description:'Estime la puissance d’un deck Magic: The Gathering Commander avec simulations Monte Carlo, synergies, accès au mana et distribution de puissance lisible.'},
    '/pourquoi':{title:'Pourquoi Aeon Scorer ? — La puissance Commander au-delà des brackets',description:'Pourquoi les brackets Commander et les notes subjectives ne suffisent pas à comparer les sorties d’un deck, et comment Aeon Scorer modélise une distribution de puissance.'},
    '/methodologie':{title:'Méthodologie — Aeon Scorer',description:'Comment Aeon Scorer analyse un deck Commander : rôles des cartes, packages, accès au mana, Monte Carlo, calibration et limites connues.'},
    '/a-propos':{title:'À propos — Aeon Scorer',description:'L’origine d’Aeon Scorer, un projet open source indépendant pour mieux comparer la puissance des decks Magic: The Gathering Commander.'}
  }
}
const t=(lang,en,fr)=>lang==='fr'?fr:en
function PageHead({eyebrow,title,lead}){return <header className="contentHead"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{lead}</p></div></header>}
function Callout({children}){return <div className="contentCallout">{children}</div>}

export function WhyPage({navigate,lang='en'}){
  const L=(en,fr)=>t(lang,en,fr)
  return <div className="contentPage">
    <PageHead eyebrow={L('WHY AEON SCORER?','POURQUOI AEON SCORER ?')} title={L('Commander power is more than a bracket.','La puissance Commander ne se résume pas à un bracket.')} lead={L('Commander has five official Brackets, and they are useful for describing intended play experience. Aeon Scorer answers a different question: what can this specific deck actually produce, and how consistently?','Commander possède cinq brackets officiels, utiles pour décrire une expérience de jeu attendue. Aeon Scorer répond à une autre question : que peut réellement produire ce deck précis, et avec quelle régularité ?')}/>
    <section className="panel proseGrid"><div><h2>{L('The problem','Le problème')}</h2><p>{L('Brackets are deliberately broad. Two decks in the same bracket can still differ sharply in speed, consistency, interaction, combo access or peak output. Subjective “power level” numbers have the same problem: they compress too much information into one label.','Les brackets sont volontairement larges. Deux decks du même bracket peuvent encore différer fortement en vitesse, régularité, interaction, accès aux combos ou pic de puissance. Les notes subjectives de « power level » ont le même problème : elles compressent trop d’informations dans une seule étiquette.')}</p><p>{L('For table matching, it matters how a deck behaves when it draws poorly, normally and extremely well—not only which category it belongs to.','Pour équilibrer une table, il faut savoir comment le deck se comporte quand il pioche mal, normalement ou extrêmement bien — pas seulement à quelle catégorie il appartient.')}</p></div><div><h2>{L('The idea','L’idée')}</h2><p>{L('Aeon Scorer turns a Commander decklist into a power distribution. The main result intentionally stays focused on four readable values:','Aeon Scorer transforme une decklist Commander en distribution de puissance. Le résultat principal reste volontairement centré sur quatre valeurs lisibles :')}</p><div className="fourMetricExplainer"><span><b>{L('Median','Médiane')}</b><small>{L('usual power','puissance habituelle')}</small></span><span><b>P20</b><small>{L('low output','sortie basse')}</small></span><span><b>P80</b><small>{L('high output','sortie haute')}</small></span><span><b>{L('Peak','Pic')}</b><small>{L('upper potential','haut de potentiel')}</small></span></div></div></section>
    <Callout><b>{L('Example:','Exemple :')}</b> {L('a deck at ','un deck à ')}<strong>55 [45–65] · {L('peak','pic')} 85</strong> {L('is not equivalent to a deck at ','n’est pas équivalent à un deck à ')}<strong>55 [51–60] · {L('peak','pic')} 68</strong>. {L('Their medians match; their table experience may not.','Leur médiane est identique ; leur expérience de table peut être très différente.')}</Callout>
    <section className="panel prose"><h2>{L('What Aeon Scorer is trying to answer','Ce qu’Aeon Scorer cherche à répondre')}</h2><p>{L('The question is not “which Bracket is this deck?” or “how skilled is the builder?” It is: ','La question n’est pas « à quel bracket appartient ce deck ? » ni « le joueur sait-il bien construire ? ». C’est : ')}<b>{L('what outputs can this deck structurally produce, how consistently, and how quickly?','quelles sorties ce deck est-il structurellement capable de produire, avec quelle régularité, et à quelle vitesse ?')}</b></p><p>{L('The score is not a win rate. A 66 does not win 66% of its games. It is a calibrated structural power scale meant to improve pregame discussion.','Le score n’est pas un winrate. Un 66 ne gagne pas 66 % de ses parties. C’est une échelle de puissance structurelle calibrée pour améliorer la discussion d’avant-partie.')}</p></section>
    <section className="panel prose"><h2>{L('Practical use','Le but pratique')}</h2><p>{L('Match medians first. Then compare how much the P20–P80 ranges overlap and whether one deck has a much higher peak or a known combo. The goal is not to replace the five Commander Brackets; it is to add a finer, deck-specific measurement beside them.','Rapproche d’abord les médianes. Ensuite compare le chevauchement P20–P80 et regarde si un deck possède un pic beaucoup plus haut ou une combo connue. Le but n’est pas de remplacer les cinq brackets Commander, mais d’ajouter une mesure plus fine et spécifique au deck à côté d’eux.')}</p><button className="inlineCta" onClick={()=>navigate('/')}>{L('Analyze a deck','Analyser un deck')}</button></section>
  </div>
}

export function MethodPage({navigate,lang='en'}){
  const L=(en,fr)=>t(lang,en,fr)
  return <div className="contentPage">
    <PageHead eyebrow={L('METHODOLOGY','MÉTHODOLOGIE')} title={L('An explainable score, not a black box.','Un score explicable, pas une boîte noire.')} lead={L('Aeon Scorer does not memorize decklists and does not assign a fixed score by card name. It builds functional roles, synergy packages and access windows, then simulates thousands of sequences.','Aeon Scorer ne mémorise pas des decklists et n’attribue pas une note fixe par nom de carte. Il construit des rôles fonctionnels, des packages et des fenêtres d’accès, puis simule des milliers de séquences.')}/>
    <section className="methodSteps"><article className="panel"><span>01</span><h2>{L('Understand the cards','Comprendre les cartes')}</h2><p>{L('Oracle text and card type are converted into functional roles: draw, interaction, tutors, fast mana, blink, recursion, token payoffs and more. The engine tries to distinguish a real role from a word merely mentioned in rules text.','Le texte Oracle et le type de chaque carte sont convertis en rôles fonctionnels : pioche, interaction, tutor, fast mana, blink, récursion, payoff tokens, etc. Le moteur essaie de distinguer un rôle réel d’un simple mot cité dans le texte.')}</p></article><article className="panel"><span>02</span><h2>{L('Build synergy packages','Construire les packages')}</h2><p>{L('Roles are linked into producer → payoff subsystems: Blink/ETB, Constellation, tokens, sacrifice, graveyard, counters, commander acceleration and more. An operational package requires distinct pieces and a plausible mana window.','Les rôles sont reliés en sous-systèmes producteur → payoff : Blink/ETB, Constellation, tokens, sacrifice, cimetière, marqueurs, accélération du commandant… Un package opérationnel exige des pièces distinctes et une fenêtre de mana plausible.')}</p></article><article className="panel"><span>03</span><h2>{L('Simulate access','Simuler l’accès')}</h2><p>{L('Thousands of Monte Carlo sequences model opening hands, Commander mulligans, lands, persistent or burst mana, commander access, interaction and packages through turn 7.','Des milliers de séquences Monte Carlo modélisent les mains, mulligans Commander, terrains, mana persistant ou burst, accès au commandant, interaction et packages jusqu’au tour 7.')}</p></article><article className="panel"><span>04</span><h2>{L('Produce a distribution','Produire une distribution')}</h2><p>{L('The sequences become a median, P20, P80 and peak. Speed, consistency, explosiveness, synergy, interaction and recovery dimensions are then used to explain the result.','Les séquences deviennent une médiane, un P20, un P80 et un pic. Les dimensions de vitesse, consistance, explosivité, synergie, interaction et reprise servent ensuite à expliquer le résultat.')}</p></article></section>
    <section className="panel prose"><h2>{L('v3.1 calibration and validation','Calibration et validation v3.1')}</h2><p>{L('v3.1 was validated on a real corpus of ','La v3.1 a été validée sur un corpus réel de ')}<b>38 {L('decks','decks')}</b>: 15 {L('precons, 15 cEDH lists with 15 distinct commanders, and 8 user/public decks. The precons span multiple years so the anchor is not biased toward only old products.','précons, 15 listes cEDH avec 15 commandants distincts et 8 decks utilisateur/publics. Les précons couvrent plusieurs années pour éviter un corpus uniquement ancien.')}</p><p>{L('The same final head passed micro-semantic tests, metamorphic checks, an adversarial audit, production build, 1,800- and 3,200-sequence benchmarks, and convergence testing. Final corpus medians are about ','Le même head final a passé les tests micro-sémantiques, métamorphiques, un audit adversarial, le build production, les benchmarks à 1 800 et 3 200 séquences ainsi qu’un test de convergence. Les médianes centrales du corpus final sont environ ')}<b>49 {L('for precons','pour les précons')}</b> {L('and','et')} <b>78 {L('for cEDH lists','pour les listes cEDH')}</b>. {L('These are calibration references, not universal thresholds.','Ce sont des repères de calibration, pas des seuils universels.')}</p></section>
    <section className="panel prose"><h2>{L('What the engine does not claim to do','Ce que le moteur ne prétend pas faire')}</h2><p>{L('Aeon Scorer is not a complete Magic rules engine. It does not simulate a true four-player table, politics, every target, a complete stack or all opponent decisions. Tutors are detected but their targets are not executed dynamically. Some alternate-cost and highly contextual mana mechanics remain approximations.','Aeon Scorer n’est pas un moteur complet des règles de Magic. Il ne simule pas une vraie table à quatre, la politique, toutes les cibles, une stack complète ou toutes les décisions adverses. Les tuteurs sont détectés mais leurs cibles ne sont pas exécutées dynamiquement. Certaines mécaniques de coûts alternatifs et de mana très contextuel restent approximées.')}</p><p>{L('The combo library is intentionally high-confidence and non-exhaustive: no displayed combo does not mean “no possible combo.”','La bibliothèque de combos est volontairement haute confiance et non exhaustive : aucune combo affichée ne signifie pas « aucune combo possible ».')}</p></section>
    <section className="panel prose faq"><h2>{L('FAQ','Questions fréquentes')}</h2><details><summary>{L('Does 66 mean a 66% win rate?','66 veut dire 66 % de winrate ?')}</summary><p>{L('No. 66 is a position on Aeon Scorer’s structural scale. Game outcomes also depend on opponents, matchup, politics and piloting.','Non. 66 est une position sur l’échelle structurelle Aeon Scorer. Le résultat d’une partie dépend aussi des adversaires, du matchup, de la politique et du pilotage.')}</p></details><details><summary>{L('Why can a precon have 100 synergy?','Pourquoi un précon peut-il avoir 100 en synergie ?')}</summary><p>{L('Because synergy measures cohesion of the detected plan, not absolute power. A deck can execute a slow, low-explosiveness plan very cleanly.','Parce que la synergie mesure la cohésion du plan détecté, pas la puissance absolue. Un deck peut exécuter très proprement un plan lent et peu explosif.')}</p></details><details><summary>{L('What is analysis coverage for?','À quoi sert la couverture d’analyse ?')}</summary><p>{L('It is a quality-control signal: how much of the input data the engine could understand and classify. It is not a confidence percentage.','C’est un contrôle qualité : la part des données que le moteur a pu comprendre et classer. Ce n’est pas un pourcentage de certitude.')}</p></details><details><summary>{L('How should I compare two decks?','Comment comparer deux decks ?')}</summary><p>{L('Start with median, then compare P20–P80 and peak. Check known combos, and open the detailed diagnostic when the headline numbers need explanation.','Commence par la médiane, puis compare P20–P80 et le pic. Vérifie ensuite les combos connues et ouvre le diagnostic détaillé si les chiffres principaux ont besoin d’être expliqués.')}</p></details></section>
    <button className="inlineCta" onClick={()=>navigate('/')}>{L('Test a decklist','Tester une decklist')}</button>
  </div>
}

export function AboutPage({lang='en'}){
  const L=(en,fr)=>t(lang,en,fr)
  return <div className="contentPage">
    <PageHead eyebrow={L('ABOUT','À PROPOS')} title={L('An independent project for Commander tables.','Un projet indépendant pour les tables Commander.')} lead={L('Aeon Scorer is maintained by megazz31 and developed publicly on GitHub. It started from a player frustration: broad categories and subjective ratings are not enough when you want to compare specific decks seriously.','Aeon Scorer est porté par megazz31 et développé publiquement sur GitHub. Le projet part d’une frustration de joueur : les catégories larges et les notes subjectives ne suffisent pas quand on veut comparer sérieusement des decks précis.')}/>
    <section className="panel prose"><h2>{L('Why the project is public','Pourquoi le projet est public')}</h2><p>{L('The engine is visible so its choices can be understood, criticized and improved. Detection errors, mechanical limits and calibration decisions are not hidden; they are part of the work.','Le moteur est visible pour que ses choix puissent être compris, critiqués et améliorés. Les erreurs de détection, limites mécaniques et calibrations ne sont pas cachées : elles font partie du travail.')}</p><p>{L('The public repository also lets players report misread decks, propose test cases or open Pull Requests. Production code remains controlled by the repository owner: public does not mean anyone can modify ','Le dépôt public permet aussi aux joueurs de signaler un deck mal interprété, proposer un cas de test ou ouvrir une Pull Request. Le code de production reste contrôlé par le propriétaire du dépôt : public ne signifie pas que n’importe qui peut modifier directement ')}<code>main</code>.</p></section>
    <section className="panel prose"><h2>{L('Project principles','Principes du projet')}</h2><ul><li><b>{L('Explainable:','Explicable :')}</b> {L('a score should trace back to cards, packages and access windows.','un score doit pouvoir être relié à des cartes, packages et fenêtres d’accès.')}</li><li><b>{L('Probabilistic:','Probabiliste :')}</b> {L('a deck does not have one output; it has a distribution.','un deck n’a pas une seule sortie ; il a une distribution.')}</li><li><b>{L('Practical:','Pratique :')}</b> {L('the main screen should help choose a table, not bury players under metrics.','l’écran principal doit aider à choisir une table, pas noyer le joueur sous des métriques.')}</li><li><b>{L('Revisable:','Révisable :')}</b> {L('a test that reveals a real error should be able to change the model.','un test qui révèle une erreur réelle doit pouvoir faire évoluer le modèle.')}</li></ul></section>
    <section className="panel projectLinks"><div><span className="eyebrow">{L('PROJECT','PROJET')}</span><h2>Aeon Scorer v3.1</h2><p>JavaScript · React/Vite · Scryfall · Monte Carlo · Commander/EDH</p></div><div className="linkStack"><a href="https://aeon-scorer.vercel.app" target="_blank" rel="noreferrer">{L('Open the app ↗','Ouvrir l’application ↗')}</a><a href="https://github.com/megazz31/aeon-scorer" target="_blank" rel="noreferrer">{L('View source on GitHub ↗','Voir le code sur GitHub ↗')}</a></div></section>
  </div>
}
