const SUPABASE_URL='https://jrzzlcklctmqgemepucs.supabase.co'
const PUBLISHABLE_KEY='sb_publishable_wrSl8JoCrvkBhh3hN6LiAg_M2yHrr1y'
const SESSION_KEY='aeon-supabase-session-v1'

const baseHeaders=()=>({apikey:PUBLISHABLE_KEY,'Content-Type':'application/json'})
const authHeaders=token=>({...baseHeaders(),...(token?{Authorization:`Bearer ${token}`}:{})})
const cleanSession=s=>s?.access_token&&s?.user?{access_token:s.access_token,refresh_token:s.refresh_token,user:s.user,expires_at:s.expires_at||Math.floor(Date.now()/1000)+(s.expires_in||3600)}:null
export const cloudConfig={url:SUPABASE_URL}

function readStored(){try{return JSON.parse(localStorage.getItem(SESSION_KEY)||'null')}catch{return null}}
function store(session){if(session)localStorage.setItem(SESSION_KEY,JSON.stringify(session));else localStorage.removeItem(SESSION_KEY)}
async function payload(res){const text=await res.text();let body=null;try{body=text?JSON.parse(text):null}catch{body={message:text}}if(!res.ok)throw new Error(body?.msg||body?.message||body?.error_description||body?.error||`Supabase HTTP ${res.status}`);return body}
async function refresh(session){if(!session?.refresh_token)return null;try{const res=await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=refresh_token`,{method:'POST',headers:baseHeaders(),body:JSON.stringify({refresh_token:session.refresh_token})});const next=cleanSession(await payload(res));store(next);return next}catch{store(null);return null}}
export async function restoreSession(){let s=readStored();if(!s)return null;if(!s.expires_at||s.expires_at<Math.floor(Date.now()/1000)+300)s=await refresh(s);if(!s)return null;try{const res=await fetch(`${SUPABASE_URL}/auth/v1/user`,{headers:authHeaders(s.access_token)});const user=await payload(res);s={...s,user};store(s);return s}catch{return refresh(s)}}
export async function signIn(email,password){const res=await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=password`,{method:'POST',headers:baseHeaders(),body:JSON.stringify({email,password})});const s=cleanSession(await payload(res));store(s);return s}
export async function signUp(email,password){const redirectTo='https://aeon-scorer.vercel.app';const res=await fetch(`${SUPABASE_URL}/auth/v1/signup?redirect_to=${encodeURIComponent(redirectTo)}`,{method:'POST',headers:baseHeaders(),body:JSON.stringify({email,password})});const body=await payload(res),s=cleanSession(body);if(s)store(s);return {session:s,user:body?.user||s?.user||null,needsConfirmation:!s}}
export async function signOut(session){try{if(session?.access_token)await fetch(`${SUPABASE_URL}/auth/v1/logout`,{headers:authHeaders(session.access_token),method:'POST'})}finally{store(null)}}
async function rest(path,{method='GET',body,session,prefer}={}){const headers=authHeaders(session?.access_token);if(prefer)headers.Prefer=prefer;const res=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{method,headers,body:body===undefined?undefined:JSON.stringify(body)});return payload(res)}
export async function listDecks(session){return rest(`decks?select=id,name,commander_name,original_decklist,deck_data,deck_hash,source_url,source_provider,source_deck_id,source_title,source_fingerprint,source_synced_at,last_modified,created_at,latest_analysis_at,engine_version,archived&archived=eq.false&order=last_modified.desc`,{session})}
export async function saveDeck(session,{id,name,commanderName,decklist,deckHash,engineVersion,sourceUrl=null,sourceProvider=null,sourceDeckId=null,sourceTitle=null,sourceFingerprint=null}){const row={user_id:session.user.id,name,commander_name:commanderName,original_decklist:decklist,deck_data:{commander:commanderName},deck_hash:deckHash,engine_version:engineVersion,source_url:sourceUrl,source_provider:sourceProvider,source_deck_id:sourceDeckId,source_title:sourceTitle,source_fingerprint:sourceFingerprint,source_synced_at:sourceProvider?new Date().toISOString():null,last_modified:new Date().toISOString()};if(id)return rest(`decks?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',body:row,session,prefer:'return=representation'}).then(x=>x?.[0]||null);return rest('decks',{method:'POST',body:row,session,prefer:'return=representation'}).then(x=>x?.[0]||null)}
export async function deleteDeck(session,id){await rest(`decks?id=eq.${encodeURIComponent(id)}`,{method:'DELETE',session});return true}
export async function deleteMyAnalysisData(session){return rest('rpc/aeon_delete_my_analysis_data',{method:'POST',body:{},session})}
export async function analysisHistory(session,deckId,limit=12){return rest(`analysis_runs?select=id,engine_version,semantic_version,median,p20,p80,peak,coverage,iterations,created_at,result&deck_id=eq.${encodeURIComponent(deckId)}&order=created_at.desc&limit=${Math.max(1,Math.min(50,limit))}`,{session})}
export async function deckVersions(session,deckId,limit=20){return rest(`deck_versions?select=id,deck_id,deck_hash,commander_names,decklist,source_provider,source_url,source_fingerprint,created_at&deck_id=eq.${encodeURIComponent(deckId)}&order=created_at.desc&limit=${Math.max(1,Math.min(50,limit))}`,{session})}
export async function saveDeckVersion(session,{deckId,deckHash,commanderNames,decklist,sourceProvider=null,sourceUrl=null,sourceFingerprint=null}){const row={deck_id:deckId,user_id:session.user.id,deck_hash:deckHash,commander_names:commanderNames||[],decklist,source_provider:sourceProvider,source_url:sourceUrl,source_fingerprint:sourceFingerprint};return rest('deck_versions',{method:'POST',body:row,session,prefer:'resolution=ignore-duplicates,return=representation'})}
async function sha256Hex(value){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(String(value)));return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join('')}
export async function hashDeck(decklist,commander){const normalized=`${String(commander||'').trim().toLowerCase()}\n${String(decklist||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean).sort((a,b)=>a.localeCompare(b)).join('\n')}`;return sha256Hex(normalized)}
export async function hashPodFingerprint(codes=[]){return sha256Hex([...new Set(codes.map(x=>String(x||'').trim().toLowerCase()).filter(Boolean))].sort().join('|'))}
export async function recordAnalysis(session,data){const headers=authHeaders(session?.access_token);const res=await fetch(`${SUPABASE_URL}/functions/v1/record-analysis`,{method:'POST',headers,body:JSON.stringify(data)}),out=await payload(res);if(typeof window!=='undefined'&&typeof window.dispatchEvent==='function'&&typeof CustomEvent!=='undefined')queueMicrotask(()=>{try{window.dispatchEvent(new CustomEvent('aeon-analysis-recorded',{detail:out}))}catch{}});return out}
export async function createAnalysisShare(analysisId,{gameChangers=[],bracketSignals={},comboSummary=null,productIntelligence={}}={}){const body={p_analysis_id:analysisId,p_game_changers:gameChangers,p_bracket_signals:bracketSignals,p_combo_summary:comboSummary,p_product_intelligence:productIntelligence},session=await restoreSession().catch(()=>null);return rest('rpc/aeon_create_analysis_share',{method:'POST',body,session}).then(x=>typeof x==='string'?x:x?.share_code||x)}
export async function loadAnalysisShare(code){const rows=await rest(`analysis_shares?select=share_code,deck_name,commander_names,engine_version,semantic_version,iterations,median,p20,p80,peak,coverage,dimensions,packages,combo_summary,game_changers,bracket_signals,product_intelligence,created_at&share_code=eq.${encodeURIComponent(code)}&revoked_at=is.null&limit=1`);return rows?.[0]||null}
export async function submitAnalysisFeedback(analysisId,category,message=''){const session=await restoreSession().catch(()=>null);return rest('rpc/aeon_submit_analysis_feedback',{method:'POST',body:{p_analysis_id:analysisId,p_category:category,p_message:message},session})}
export async function createMatchSession(maxPlayers=64){const session=await restoreSession();if(!session)throw new Error('authentication_required');return rest('rpc/aeon_create_match_session',{method:'POST',body:{p_max_players:Math.max(4,Math.min(64,Number(maxPlayers)||64))},session})}
export async function joinMatchSession(code,shareCode){const session=await restoreSession().catch(()=>null);return rest('rpc/aeon_join_match_session',{method:'POST',body:{p_code:String(code||'').trim().toLowerCase(),p_share_code:String(shareCode||'').trim().toLowerCase()},session})}
export async function loadMatchSession(code){const session=await restoreSession().catch(()=>null);return rest('rpc/aeon_read_match_session',{method:'POST',body:{p_code:String(code||'').trim().toLowerCase()},session})}
export async function setMatchSessionStatus(code,organizerToken,status){const session=await restoreSession().catch(()=>null);return rest('rpc/aeon_set_match_session_status',{method:'POST',body:{p_code:String(code||'').trim().toLowerCase(),p_organizer_token:String(organizerToken||''),p_status:status},session})}
export async function submitGameObservation({shareCodes=[],podModelVersion,engineVersions=[],semanticVersions=[],prediction=null,turnBand,winType,balance,dominantEvent='none'}){
  const codes=[...new Set(shareCodes.map(x=>String(x||'').trim().toLowerCase()).filter(Boolean))]
  if(codes.length<2||codes.length>8)throw new Error('invalid_pod_size')
  if(!prediction||![prediction.riskScore,prediction.podMismatch,prediction.threatGap].every(x=>Number.isFinite(Number(x))))throw new Error('prediction_required')
  const fingerprint=await hashPodFingerprint(codes),session=await restoreSession().catch(()=>null),riskScore=Math.max(0,Math.min(100,Math.round(Number(prediction.riskScore)))),podMismatch=Math.max(0,Math.min(100,Math.round(Number(prediction.podMismatch)))),threatGap=Math.max(0,Math.min(100,Math.round(Number(prediction.threatGap)))),derivedRiskLevel=riskScore>=70?'high':riskScore>=40?'moderate':'low',riskLevel=['low','moderate','high'].includes(prediction.riskLevel)?prediction.riskLevel:derivedRiskLevel
  if(riskLevel!==derivedRiskLevel)throw new Error('invalid_risk_level')
  return rest('rpc/aeon_submit_game_observation',{method:'POST',body:{p_pod_fingerprint:fingerprint,p_pod_size:codes.length,p_pod_model_version:podModelVersion,p_engine_versions:[...new Set(engineVersions)].slice(0,8),p_semantic_versions:[...new Set(semanticVersions)].slice(0,8),p_predicted_risk_score:riskScore,p_predicted_risk_level:riskLevel,p_predicted_pod_mismatch:podMismatch,p_predicted_threat_gap:threatGap,p_turn_band:turnBand,p_win_type:winType,p_balance:balance,p_dominant_event:dominantEvent},session})
}
